In [3]:
import numpy as np

In [5]:
# Standardization
from sklearn.preprocessing import StandardScaler

data = np.array([
    [1, 200000],  # 1 bedroom, $200k salary
    [2, 300000],  # 2 bedrooms, $300k salary
    [3, 250000],  # 3 bedrooms, $250k salary
    [4, 400000]   # 4 bedrooms, $400k salary
])

print("BEFORE scaling:")
print(data)
print("\nMeans:", data.mean(axis=0))
print("Std devs:", data.std(axis=0))

# Create and apply scaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print("\n" + "="*50)
print("AFTER scaling:")
print(scaled_data)
print("\nMeans:", scaled_data.mean(axis=0))  # Now ~0
print("Std devs:", scaled_data.std(axis=0))  # Now ~1

BEFORE scaling:
[[     1 200000]
 [     2 300000]
 [     3 250000]
 [     4 400000]]

Means: [2.500e+00 2.875e+05]
Std devs: [1.11803399e+00 7.39509973e+04]

AFTER scaling:
[[-1.34164079 -1.18321596]
 [-0.4472136   0.16903085]
 [ 0.4472136  -0.50709255]
 [ 1.34164079  1.52127766]]

Means: [0. 0.]
Std devs: [1. 1.]


In [11]:
# Normalization

from sklearn.preprocessing import MinMaxScaler

# Same data
data = np.array([
    [1, 200000],
    [2, 300000],
    [3, 250000],
    [4, 400000]
])

print("BEFORE scaling:")
print(data)

# Create and apply scaler
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

print("\n" + "="*50)
print("AFTER scaling (all values 0-1):")
print(scaled_data)
print("\nMin values:", scaled_data.min(axis=0))  # Now 0
print("Max values:", scaled_data.max(axis=0))    # Now 1

BEFORE scaling:
[[     1 200000]
 [     2 300000]
 [     3 250000]
 [     4 400000]]

AFTER scaling (all values 0-1):
[[0.         0.        ]
 [0.33333333 0.5       ]
 [0.66666667 0.25      ]
 [1.         1.        ]]

Min values: [0. 0.]
Max values: [1. 1.]


In [12]:
# Label Encoding 

from sklearn.preprocessing import LabelEncoder

# Categories as text
colors = ['red', 'blue', 'green', 'red', 'green', 'blue']

print("BEFORE encoding:")
print(colors)

# Create and apply encoder
encoder = LabelEncoder()
colors_encoded = encoder.fit_transform(colors)

print("\nAFTER encoding:")
print(colors_encoded)  # [2, 0, 1, 2, 1, 0]

# See the mapping
print("\nMapping:")
for i, label in enumerate(encoder.classes_):
    print(f"{label} → {i}")

# Convert back to original
colors_decoded = encoder.inverse_transform(colors_encoded)
print("\nDecoded back:")
print(colors_decoded)

BEFORE encoding:
['red', 'blue', 'green', 'red', 'green', 'blue']

AFTER encoding:
[2 0 1 2 1 0]

Mapping:
blue → 0
green → 1
red → 2

Decoded back:
['red' 'blue' 'green' 'red' 'green' 'blue']


In [14]:
# OneHot ENcoder

from sklearn.preprocessing import OneHotEncoder

# Categories (needs 2D array)
colors = np.array(['red', 'blue', 'green', 'red']).reshape(-1, 1)

print("BEFORE encoding:")
print(colors.ravel())

# Create and apply encoder
encoder = OneHotEncoder(sparse_output=False)
colors_encoded = encoder.fit_transform(colors)

print("\nAFTER encoding:")
print(colors_encoded)
print("\nColumn names:", encoder.categories_[0])

# Each row is now: [is_blue, is_green, is_red]
# red   → [0, 0, 1]
# blue  → [1, 0, 0]
# green → [0, 1, 0]

BEFORE encoding:
['red' 'blue' 'green' 'red']

AFTER encoding:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Column names: ['blue' 'green' 'red']


In [24]:
# Exercise 1

from sklearn.preprocessing import StandardScaler, MinMaxScaler

data = np.array([
    [0.5, 100],
    [1.0, 200],
    [1.5, 150],
    [2.0, 250]
])

std_scaler = StandardScaler()
std_scaled = std_scaler.fit_transform(data)
print("Mean:", std_scaled.mean())
print("Standard deviation:", std_scaled.std())

norm_scaler = MinMaxScaler()
norm_scaled = norm_scaler.fit_transform(data)
print("Min:", norm_scaled.min())
print("Max:", norm_scaled.max())

Mean: 0.0
Standard deviation: 1.0
Min: 0.0
Max: 1.0


In [42]:
# Exercise 2

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
scaler.fit(X_train)
Xtrain_scaled = scaler.transform(X_train)
Xtest_scaled = scaler.transform(X_test)
print(Xtrain_scaled.mean())
print(Xtest_scaled.mean())

3.721890520648144e-16
-0.0034440447509067654


In [74]:
# Exercise 3

from sklearn.preprocessing import LabelEncoder

fruits = ['apple', 'banana', 'apple', 'orange', 'banana', 'apple']
colors = ['red', 'yellow', 'green', 'orange', 'yellow', 'red']

fruit_encoder = LabelEncoder()
color_encoder = LabelEncoder()
fruits_encoded = fruit_encoder.fit_transform(fruits)
colors_encoded = color_encoder.fit_transform(colors)
print("Fruits encoded:", fruits_encoded)
print("Colors encoded:", colors_encoded)

arr = np.array([fruits_encoded, colors_encoded])
print(arr)

print(arr[0,0])
first_fruit_decoded = fruit_encoder.inverse_transform(arr[0])
print(first_fruit_decoded[0])

Fruits encoded: [0 1 0 2 1 0]
Colors encoded: [2 3 0 1 3 2]
[[0 1 0 2 1 0]
 [2 3 0 1 3 2]]
0
apple


In [93]:
# Exercise 4

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

wine = load_wine()
X, y = wine.data, wine.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(X_train_scaled.mean())
print(X_test_scaled.mean())

knn = KNeighborsClassifier(n_neighbors=5)
model = knn.fit(X_train_scaled, y_train)

predictions = model.predict(X_test_scaled)
acc = accuracy_score(predictions, y_test)
print(acc)

8.518137945759266e-16
0.004732197662401923
0.9629629629629629
