### ODEV

 Gerekli Kütüphanelerin İndirilmesi
Jupyter Notebook dosyamızın başına aşağıdaki gibi gerekli kütüphaneleri import ederek başlayabiliriz:

In [6]:
# Gerekli kütüphanelerin yüklenmesi
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

import warnings
warnings.filterwarnings("ignore")


DataSheet_1_Nomogram for predicting invasive lung adenocarcinoma in small solitary pulmonary nodules veri setini yüklemek için bir CSV dosyası olarak indirin veya veri setini doğrudan yüklemek için pandas kütüphanesini kullanın.

In [12]:
# Veri setinin yüklenmesi
data = pd.read_csv('DataSheet_1_Nomogram for predicting invasive lung adenocarcinoma in small solitary pulmonary nodules.csv')

In [14]:
print(data)

        ID  Tumor_Invasiveness  Hypertension  Diabetes  COPD  Blood_Type  \
0        2                   1             0         0     0           1   
1        3                   0             1         0     0           3   
2        4                   0             0         0     0           0   
3        5                   0             0         0     0           1   
4        6                   0             0         0     0           0   
...    ...                 ...           ...       ...   ...         ...   
1101  1377                   1             0         0     0           0   
1102  1378                   1             1         0     0           1   
1103  1379                   1             0         0     0           3   
1104  1380                   1             0         0     0           3   
1105  1381                   0             0         0     0           0   

      Albumin  Lymphocyte    PNI  Neutrophil  ...  Spiculation  \
0        65.9        

In [15]:
# İlk birkaç satırı görüntüleme
data.head()

,ID,Tumor_Invasiveness,Hypertension,Diabetes,COPD,Blood_Type,Albumin,Lymphocyte,PNI,Neutrophil,...,Spiculation,Cavitation_Sign,Calcification,Vascular_Penetration_Sign,Pleural_Adhesions,Bronchus_Sign,Lobulation,Lymph_Node_Enlargement_Sign,Pleural_Effusion_Sign,CTR
0,2,1,0,0,0,1,65.9,2.01,75.95,5.38,...,1,0,0,0,1,0,0,1,0,0.87
1,3,0,1,0,0,3,66.2,1.59,74.15,2.80,...,0,0,0,1,1,0,1,1,0,0.33
2,4,0,0,0,0,0,57.2,1.61,65.25,3.17,...,0,0,0,1,0,0,0,0,0,0.00
3,5,0,0,0,0,1,57.7,1.70,66.20,1.99,...,0,0,1,0,0,0,0,0,0,0.36
4,6,0,0,0,0,0,64.2,1.36,71.00,2.77,...,0,0,0,0,0,0,0,0,0,0.00


Veri setini inceleyerek, sütun isimlerini ve veri türlerini gözden geçerek. Eksik veri olup olmadığını kontrol edelim.

In [16]:
# Sütunlar ve veri türleri
print(data.info())



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1106 entries, 0 to 1105
Data columns (total 56 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   ID                           1106 non-null   int64  
 1   Tumor_Invasiveness           1106 non-null   int64  
 2   Hypertension                 1106 non-null   int64  
 3   Diabetes                     1106 non-null   int64  
 4   COPD                         1106 non-null   int64  
 5   Blood_Type                   1106 non-null   int64  
 6   Albumin                      1106 non-null   float64
 7   Lymphocyte                   1106 non-null   float64
 8   PNI                          1106 non-null   float64
 9   Neutrophil                   1106 non-null   float64
 10  Eosinophil                   1106 non-null   float64
 11  Basophil                     1106 non-null   float64
 12  Monocyte                     1106 non-null   float64
 13  Erythrocyte       

In [17]:
# Eksik verileri kontrol etme
print(data.isnull().sum())


ID                             0
Tumor_Invasiveness             0
Hypertension                   0
Diabetes                       0
COPD                           0
Blood_Type                     0
Albumin                        0
Lymphocyte                     0
PNI                            0
Neutrophil                     0
Eosinophil                     0
Basophil                       0
Monocyte                       0
Erythrocyte                    0
Hemoglobin                     0
Platelet                       0
NLR                            0
PLR                            0
MLR                            0
dNLR                           0
NLPR                           0
SIRI                           0
AISI                           0
SII                            0
PIV                            0
Blood_Sugar                    0
Complement_C1q                 0
LDH                            0
SA                             0
x5_nt                          0
Pro_GRP   

Eğer eksik veri varsa, ilgili sütunları doldurma veya kaldırma işlemi yapılmalıdır. Ancak bu veri setinde eksik veri olmadığını varsayalım.

Bağımsız değişkenleri (özellikler) ve bağımlı değişkeni (hedef) belirleyelim. Bu veri setinde, Tumor_Invasiveness sütunu hedef değişkendir.

In [20]:
# Özellikler ve hedef değişkenin ayrılması
X = data.drop("Pleural_Adhesions", axis=1)


In [19]:
print(X)

        ID  Hypertension  Diabetes  COPD  Blood_Type  Albumin  Lymphocyte  \
0        2             0         0     0           1     65.9        2.01   
1        3             1         0     0           3     66.2        1.59   
2        4             0         0     0           0     57.2        1.61   
3        5             0         0     0           1     57.7        1.70   
4        6             0         0     0           0     64.2        1.36   
...    ...           ...       ...   ...         ...      ...         ...   
1101  1377             0         0     0           0     67.5        1.66   
1102  1378             1         0     0           1     60.3        0.54   
1103  1379             0         0     0           3     63.9        2.79   
1104  1380             0         0     0           3     67.7        1.84   
1105  1381             0         0     0           0     56.5        2.03   

        PNI  Neutrophil  Eosinophil  ...  Spiculation  Cavitation_Sign  \
0

In [23]:
y = data["Tumor_Invasiveness"]

In [24]:
print(y)

0       1
1       0
2       0
3       0
4       0
       ..
1101    1
1102    1
1103    1
1104    1
1105    0
Name: Tumor_Invasiveness, Length: 1106, dtype: int64


Eğitim ve test setlerini %80 eğitim, %20 test olacak şekilde ayıralım.

In [25]:
# Eğitim ve test setlerine ayırma
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [26]:
print(X_train, X_test, y_train, y_test)

        ID  Tumor_Invasiveness  Hypertension  Diabetes  COPD  Blood_Type  \
773   1012                   1             1         0     0           1   
728    963                   1             1         1     0           0   
867   1114                   1             1         0     0           1   
507    718                   0             0         1     0           2   
319    435                   1             1         0     0           0   
...    ...                 ...           ...       ...   ...         ...   
466    654                   0             0         0     0           0   
121    146                   0             1         0     0           0   
1044  1311                   0             0         0     0           3   
1095  1371                   0             0         0     0           1   
860   1107                   1             0         0     0           3   

      Albumin  Lymphocyte    PNI  Neutrophil  ...  Shape  Spiculation  \
773      57.8 

Her bir modeli eğitim verisi üzerinde eğiteceğiz ve test verisi üzerinde performanslarını değerlendireceğiz.

 Çoklu Lineer Regresyon (MLR)

In [27]:
# Çoklu Lineer Regresyon Modeli
mlr = LinearRegression()
mlr.fit(X_train, y_train)
y_pred_mlr = mlr.predict(X_test)


In [28]:
y_pred_mlr

array([ 8.14031426e-14, -2.07950778e-13,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  2.50516948e-13,  2.49087586e-13,  9.54759357e-14,
       -1.32268810e-13,  3.14109051e-14,  2.24836756e-13,  1.67107199e-13,
       -1.07999298e-13,  1.00000000e+00, -2.23873441e-14, -3.96502108e-14,
        3.83660920e-13,  1.00000000e+00,  1.00000000e+00,  2.19458299e-13,
       -2.11185224e-14, -1.55887572e-14,  1.00000000e+00, -3.45125093e-15,
        1.00000000e+00, -4.51024857e-13, -4.05519021e-13, -2.76911823e-13,
        1.00000000e+00, -5.00367349e-14,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00, -1.83587506e-13,  1.00000000e+00, -1.06798749e-13,
        1.00000000e+00,  3.15594914e-13, -2.39835182e-13,  1.00000000e+00,
        1.00000000e+00, -1.08060123e-13,  2.08367017e-13,  1.00000000e+00,
        3.16636088e-13,  1.00000000e+00,  1.00000000e+00,  1.34188740e-13,
        1.45427791e-13,  1.22744063e-13,  1.51132087e-13, -3.01522170e-14,
        1.00000000e+00,  

Polinom Regresyon (3. derece)

In [29]:
# Polinom özellikler (3. derece)
poly_features = PolynomialFeatures(degree=3)
X_poly_train = poly_features.fit_transform(X_train)
X_poly_test = poly_features.transform(X_test)

# Polinom Regresyon Modeli
plr = LinearRegression()
plr.fit(X_poly_train, y_train)
y_pred_plr = plr.predict(X_poly_test)


In [30]:
y_pred_plr

array([ 1.99368337e-01,  9.48955986e-02,  1.20976291e+00, -4.26837356e-01,
        9.60952091e-01,  1.41548955e-01,  1.71768392e-02, -2.27725237e-02,
        5.49503724e-02,  1.24000004e-01,  6.95582833e-02,  5.88589641e-02,
       -2.80312885e-01,  1.01807150e+00,  1.94586213e-01, -6.29355352e-02,
       -1.29469588e-01,  1.04099501e+00,  1.07813412e+00,  1.92485641e-03,
        5.66254562e-02,  4.08497739e-02,  9.78970803e-01,  2.40600738e-01,
        9.58823371e-01,  1.40318768e-01,  5.63001854e-01, -2.75667652e-01,
        9.81996396e-01,  2.94464745e-01,  1.02562131e+00,  9.40589791e-01,
        9.43755475e-01,  8.79846090e-03,  1.34191548e+00,  4.24025270e-02,
        1.08299986e+00, -1.30248953e-01, -8.25824696e-02,  1.22890697e+00,
        1.28115894e+00, -2.47274853e-02, -1.19660038e-01,  1.05135644e+00,
        8.47392828e-02,  9.91021950e-01,  7.97010534e-01, -1.02309497e-02,
       -5.98524580e-02, -6.66790259e-02, -8.52702609e-02,  1.07496864e-01,
        1.08748664e+00, -

Karar Ağacı (DT)

In [31]:
# Karar Ağacı Modeli
dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)


In [32]:
y_pred_dt

array([0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0.,
       1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1.])

 Rastgele Orman (RF)

In [33]:
# Rastgele Orman Modeli
rf = RandomForestRegressor(random_state=42, n_estimators=100)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)


In [34]:
y_pred_rf

array([0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0.,
       1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1.])

Her bir model için r2, mae, mape, mse skorlarını hesaplayacağız.

In [35]:
# Skor hesaplama fonksiyonu
def evaluate_model(y_test, y_pred):
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    return r2, mae, mse, mape

# Model değerlendirmeleri
results = {
    "MLR": evaluate_model(y_test, y_pred_mlr),
    "PLR (3rd Degree)": evaluate_model(y_test, y_pred_plr),
    "DT": evaluate_model(y_test, y_pred_dt),
    "RF": evaluate_model(y_test, y_pred_rf)
}

# Sonuçları DataFrame olarak görüntüleme
results_df = pd.DataFrame(results, index=["R2", "MAE", "MSE", "MAPE"])
print(results_df)


               MLR  PLR (3rd Degree)   DT   RF
R2    1.000000e+00     -4.591511e+04  1.0  1.0
MAE   2.768913e-13      8.450445e+00  0.0  0.0
MSE   4.495197e-25      1.144549e+04  0.0  0.0
MAPE           inf               inf  0.0  0.0


Her bir modelin performansını analiz edin. R2 değeri 1'e ne kadar yakınsa model o kadar başarılıdır. MAE, MSE ve MAPE ise hataların boyutunu gösterir, düşük değerler daha iyi performans anlamına gelir.