In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
data = {'Position': ['CEO','Chairman','Director','Senior Manager','Junior Manager','Intern'],
        'Level': [1,2,3,4,5,6],
        'Salary': [50000,80000,110000,150000,200000,250000]}

df = pd.DataFrame(data)
df

,Position,Level,Salary
0,CEO,1,50000
1,Chairman,2,80000
2,Director,3,110000
3,Senior Manager,4,150000
4,Junior Manager,5,200000
5,Intern,6,250000


In [3]:
X = df.iloc[:,1:2].values
y = df.iloc[:,2].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

print("X_train:\n", X_train)
print("y_train:\n", y_train)
print("X_test:\n", X_test)
print("y_test:\n", y_test)

regressor = LinearRegression()
regressor.fit(X_train, y_train)

print("Coefficients:", regressor.coef_)
print("Intercept:", regressor.intercept_)

X_train:
 [[2]
 [4]
 [1]
 [5]]
y_train:
 [ 80000 150000  50000 200000]
X_test:
 [[6]
 [3]]
y_test:
 [250000 110000]
Coefficients: [37000.]
Intercept: 9000.0
