# Data validation and pre-processing technique

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
#import library packages
import pandas as p
import numpy as n

In [3]:
#Load given dataset
data = p.read_csv("demo1.csv")

Before drop the given dataset

In [5]:
data.head()

,slug,symbol,name,date,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
0,ethereum,ETH,Ethereum,8/7/2015,3,2.830000,3.540000,2.520000,2.770000,164329,166610555,0.2451,1.02
1,ethereum,ETH,Ethereum,8/8/2015,3,2.790000,2.800000,0.714725,0.753325,674188,45486894,0.0185,2.09
2,ethereum,ETH,Ethereum,8/9/2015,3,0.706136,0.879810,0.629191,0.701897,532170,42399573,0.2901,0.25
3,ethereum,ETH,Ethereum,8/10/2015,3,0.713989,0.729854,0.636546,0.708448,405283,42818364,0.7706,0.09
4,ethereum,ETH,Ethereum,8/11/2015,3,0.708087,1.130000,0.663235,1.070000,1463100,64569288,0.8715,0.47


In [6]:
data.shape

(1078, 13)

In [7]:
data.isnull().sum()

slug            0
symbol          0
name            0
date            0
ranknow         0
open            0
high            0
low             0
close           0
volume          0
market_price    0
close_ratio     0
spread          0
dtype: int64

After drop the given dataset

In [8]:
df=data.dropna()
df.head()

,slug,symbol,name,date,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
0,ethereum,ETH,Ethereum,8/7/2015,3,2.830000,3.540000,2.520000,2.770000,164329,166610555,0.2451,1.02
1,ethereum,ETH,Ethereum,8/8/2015,3,2.790000,2.800000,0.714725,0.753325,674188,45486894,0.0185,2.09
2,ethereum,ETH,Ethereum,8/9/2015,3,0.706136,0.879810,0.629191,0.701897,532170,42399573,0.2901,0.25
3,ethereum,ETH,Ethereum,8/10/2015,3,0.713989,0.729854,0.636546,0.708448,405283,42818364,0.7706,0.09
4,ethereum,ETH,Ethereum,8/11/2015,3,0.708087,1.130000,0.663235,1.070000,1463100,64569288,0.8715,0.47


In [10]:
df.shape

(1078, 13)

In [11]:
#show columns
df.columns

Index(['slug', 'symbol', 'name', 'date', 'ranknow', 'open', 'high', 'low',
       'close', 'volume', 'market_price', 'close_ratio', 'spread'],
      dtype='object')

In [12]:
df['slug'].unique()

array(['ethereum', 'bitcoin', 'cardano', 'binance-coin'], dtype=object)

In [13]:
df['ranknow'].unique()

array([ 3,  1, 10, 16], dtype=int64)

In [14]:
df["symbol"].unique()

array(['ETH', 'BTC', 'ADA', 'BNB'], dtype=object)

In [15]:
df["open"].unique()

array([ 2.83    ,  2.79    ,  0.706136, ..., 12.61    , 13.03    ,
       12.96    ])

In [13]:
df["high"].unique()

array([3.54000e+00, 2.80000e+00, 8.79810e-01, 7.29854e-01, 1.13000e+00,
       1.29000e+00, 1.97000e+00, 2.26000e+00, 1.88000e+00, 1.70000e+00,
       1.58000e+00, 1.33000e+00, 1.32000e+00, 1.53000e+00, 1.56000e+00,
       1.48000e+00, 1.41000e+00, 1.36000e+00, 1.24000e+00, 1.20000e+00,
       1.19000e+00, 1.21000e+00, 1.37000e+00, 1.40000e+00, 1.39000e+00,
       1.35000e+00, 1.31000e+00, 1.30000e+00, 1.34000e+00, 1.28000e+00,
       1.26000e+00, 1.22000e+00, 1.17000e+00, 1.11000e+00, 1.04000e+00,
       9.49387e-01, 1.05000e+00, 9.52698e-01, 9.09204e-01, 8.88102e-01,
       9.11883e-01, 9.47741e-01, 9.57326e-01, 9.19337e-01, 9.08910e-01,
       9.08571e-01, 8.25665e-01, 7.87544e-01, 7.91277e-01, 7.25677e-01,
       6.75830e-01, 7.46722e-01, 7.34307e-01, 6.91120e-01, 7.09204e-01,
       6.93126e-01, 6.74438e-01, 6.53944e-01, 6.56301e-01, 6.33138e-01,
       6.92296e-01, 6.49022e-01, 6.39506e-01, 6.57789e-01, 6.30240e-01,
       6.12240e-01, 5.72714e-01, 5.68861e-01, 5.63460e-01, 5.522

In [16]:
df["low"].unique()

array([ 2.52    ,  0.714725,  0.629191, ..., 12.2     , 12.64    ,
       12.7     ])

In [17]:
df["close"].unique()

array([2.77000e+00, 7.53325e-01, 7.01897e-01, 7.08448e-01, 1.07000e+00,
       1.22000e+00, 1.83000e+00, 1.69000e+00, 1.57000e+00, 1.20000e+00,
       1.09000e+00, 1.26000e+00, 1.46000e+00, 1.40000e+00, 1.38000e+00,
       1.35000e+00, 1.23000e+00, 1.14000e+00, 1.16000e+00, 1.15000e+00,
       1.19000e+00, 1.18000e+00, 1.32000e+00, 1.36000e+00, 1.29000e+00,
       1.27000e+00, 1.34000e+00, 1.30000e+00, 1.25000e+00, 1.24000e+00,
       1.21000e+00, 1.17000e+00, 9.82978e-01, 1.04000e+00, 9.36003e-01,
       8.75622e-01, 9.44410e-01, 9.07175e-01, 8.74231e-01, 8.53685e-01,
       8.82391e-01, 9.38445e-01, 9.19047e-01, 9.01796e-01, 8.93406e-01,
       8.13610e-01, 7.36223e-01, 7.85964e-01, 7.20839e-01, 5.82886e-01,
       6.61146e-01, 7.38644e-01, 6.90215e-01, 6.78574e-01, 6.87171e-01,
       6.68379e-01, 6.28643e-01, 6.50645e-01, 6.09388e-01, 6.21716e-01,
       6.50628e-01, 6.27857e-01, 6.34963e-01, 6.26030e-01, 6.07655e-01,
       5.22968e-01, 5.61878e-01, 5.36495e-01, 5.47178e-01, 5.177

In [18]:
#To describe the dataframe
df.describe()

,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
count,1078.000000,1078.000000,1078.000000,1078.000000,1078.000000,1.078000e+03,1.078000e+03,1078.000000,1078.000000
mean,7.535250,140.671620,146.382083,134.116136,140.970731,7.080249e+07,3.511893e+09,0.524541,12.265872
std,6.311488,254.150371,264.755221,241.193733,254.292369,1.620918e+08,4.526472e+09,0.293256,32.991154
min,1.000000,0.018414,0.021050,0.017354,0.018539,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,1.000000,0.683412,0.731115,0.626820,0.687481,2.889678e+05,2.384042e+08,0.276625,0.060000
50%,10.000000,6.685000,8.340000,5.860000,7.190000,9.861245e+06,1.379701e+09,0.537800,0.595000
75%,16.000000,126.237500,129.315000,122.540000,126.322500,7.530740e+07,5.807221e+09,0.785400,6.797500
max,16.000000,1152.730000,1156.140000,1106.610000,1151.170000,1.713770e+09,2.888587e+10,1.000000,349.720000


In [19]:
#Checking datatype and information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1078 entries, 0 to 1077
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   slug          1078 non-null   object 
 1   symbol        1078 non-null   object 
 2   name          1078 non-null   object 
 3   date          1078 non-null   object 
 4   ranknow       1078 non-null   int64  
 5   open          1078 non-null   float64
 6   high          1078 non-null   float64
 7   low           1078 non-null   float64
 8   close         1078 non-null   float64
 9   volume        1078 non-null   int64  
 10  market_price  1078 non-null   int64  
 11  close_ratio   1078 non-null   float64
 12  spread        1078 non-null   float64
dtypes: float64(6), int64(3), object(4)
memory usage: 117.9+ KB


Checking duplicate values of dataframe

In [20]:
#Checking for duplicate data
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1073    False
1074    False
1075    False
1076    False
1077    False
Length: 1078, dtype: bool

In [21]:
#find sum of duplicate data
sum(df.duplicated())

0

In [22]:
#Checking sum of missing values
df.isnull().sum()

slug            0
symbol          0
name            0
date            0
ranknow         0
open            0
high            0
low             0
close           0
volume          0
market_price    0
close_ratio     0
spread          0
dtype: int64

In [21]:
df.columns

Index(['slug', 'symbol', 'name', 'date', 'ranknow', 'open', 'high', 'low',
       'close', 'volume', 'market_price', 'close_ratio', 'spread'],
      dtype='object')

In [23]:
df['market_price'].value_counts()

1229098150     2
166610555      1
3856859159     1
4304645594     1
4053619697     1
              ..
10025645095    1
8442962249     1
9627500113     1
10808715488    1
1455064225     1
Name: market_price, Length: 1077, dtype: int64

In [24]:
print("Minimum market_price value is:", df.market_price.min())
print("Maximum market_price value is:", df.market_price.max())

Minimum market_price value is: 0
Maximum market_price value is: 28885867828


In [24]:
p.Categorical(df['slug']).describe()

,counts,freqs
categories,,
binance-coin,306,0.283859
bitcoin,388,0.359926
cardano,241,0.223562
ethereum,143,0.132653


In [25]:
p.Categorical(df['market_price']).describe()

,counts,freqs
categories,,
0,1,0.000928
9986680,1,0.000928
10045200,1,0.000928
10406700,1,0.000928
10425000,1,0.000928
...,...,...
25915636700,1,0.000928
26147969179,1,0.000928
26630990503,1,0.000928


In [26]:
df.corr()

,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
ranknow,1.000000,-0.554967,-0.553883,-0.557980,-0.555795,0.238924,-0.190846,0.009831,-0.365617
open,-0.554967,1.000000,0.998476,0.996331,0.996178,-0.172951,0.471700,0.032038,0.728775
high,-0.553883,0.998476,1.000000,0.995825,0.998219,-0.172393,0.473178,0.043980,0.744704
low,-0.557980,0.996331,0.995825,1.000000,0.997930,-0.174601,0.472075,0.042325,0.680669
close,-0.555795,0.996178,0.998219,0.997930,1.000000,-0.173448,0.473884,0.058502,0.715019
volume,0.238924,-0.172951,-0.172393,-0.174601,-0.173448,1.000000,0.514875,0.022462,-0.106978
market_price,-0.190846,0.471700,0.473178,0.472075,0.473884,0.514875,1.000000,0.033850,0.345995
close_ratio,0.009831,0.032038,0.043980,0.042325,0.058502,0.022462,0.033850,1.000000,0.043508
spread,-0.365617,0.728775,0.744704,0.680669,0.715019,-0.106978,0.345995,0.043508,1.000000


Before Pre-Processing:

In [27]:
df.head()

,slug,symbol,name,date,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
0,ethereum,ETH,Ethereum,8/7/2015,3,2.830000,3.540000,2.520000,2.770000,164329,166610555,0.2451,1.02
1,ethereum,ETH,Ethereum,8/8/2015,3,2.790000,2.800000,0.714725,0.753325,674188,45486894,0.0185,2.09
2,ethereum,ETH,Ethereum,8/9/2015,3,0.706136,0.879810,0.629191,0.701897,532170,42399573,0.2901,0.25
3,ethereum,ETH,Ethereum,8/10/2015,3,0.713989,0.729854,0.636546,0.708448,405283,42818364,0.7706,0.09
4,ethereum,ETH,Ethereum,8/11/2015,3,0.708087,1.130000,0.663235,1.070000,1463100,64569288,0.8715,0.47


After Pre-Processing:

In [28]:
df.columns

Index(['slug', 'symbol', 'name', 'date', 'ranknow', 'open', 'high', 'low',
       'close', 'volume', 'market_price', 'close_ratio', 'spread'],
      dtype='object')

In [29]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['slug', 'symbol', 'name', 'date', 'ranknow', 'open', 'high', 'low',
       'close', 'volume', 'market_price', 'close_ratio', 'spread']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(str)


In [30]:
df.head(20)


,slug,symbol,name,date,ranknow,open,high,low,close,volume,market_price,close_ratio,spread
0,3,3,3,742,1,468,457,478,468,9,240,192,88
1,3,3,3,745,1,467,449,292,284,100,36,8,136
2,3,3,3,748,1,274,298,270,272,78,30,238,25
3,3,3,3,666,1,278,268,273,275,53,31,704,9
4,3,3,3,669,1,276,369,280,382,141,68,819,47
5,3,3,3,672,1,383,380,357,394,161,120,780,41
6,3,3,3,675,1,393,422,410,437,214,184,773,72
7,3,3,3,678,1,433,433,449,437,222,185,120,51
8,3,3,3,681,1,432,417,442,431,179,177,345,31
9,3,3,3,684,1,427,412,402,422,207,166,724,58
