<a href="https://colab.research.google.com/github/arthi0/Afame-Technologies/blob/main/HR_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Activities to complete:
 Data cleansing involves removing unnecessary columns.
 Giving the columns new names.
 Eliminating redundant entries.
 sanitizing specific columns.
 Eliminate the dataset's NaN values.
 Look for a few more changes if necessary

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split


In [2]:
df=pd.read_csv('/content/HR Data.csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

Eliminating redundant entries.

In [7]:
df.duplicated().sum()

0

In [15]:
df=df.drop_duplicates()

Eliminate the dataset's NaN values.

In [8]:
df.isnull().sum()

,0
Age,0
Attrition,0
BusinessTravel,0
DailyRate,0
Department,0
DistanceFromHome,0
Education,0
EducationField,0
EmployeeCount,0
EmployeeNumber,0


In [16]:
df=df.dropna()

In [10]:
df['EmployeeCount'].unique()

array([1])

In [11]:
df['StandardHours'].unique()

array([80])

In [12]:
df['EmployeeNumber'].unique()

array([   1,    2,    4, ..., 2064, 2065, 2068])

In [18]:
df['Over18'].unique()

array(['Y'], dtype=object)

 Data cleansing involves removing unnecessary columns.

In [24]:
df=df.drop(['EmployeeCount', 'StandardHours', 'EmployeeNumber'],axis=1)

KeyError: "['EmployeeCount', 'StandardHours', 'EmployeeNumber'] not found in axis"

In [20]:
df=df.drop(['Over18'],axis=1)

In [17]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

 Giving the columns new names.

In [21]:
df=df.rename(columns={'Attrition': 'IsAttrition',
    'BusinessTravel': 'Travel_Frequency',
    'DailyRate': 'Daily_Rate_USD',
    'Education': 'Education_Level',
    'EducationField': 'Field_Of_Study',
    'TotalWorkingYears': 'Total_Experience_Years',
    'YearsAtCompany': 'Tenure_Years',
    'YearsInCurrentRole': 'Current_Role_Years',
    'YearsSinceLastPromotion': 'Years_Since_Promotion',
    'YearsWithCurrManager': 'Manager_Years'})

 sanitizing specific columns

In [22]:
df= df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

<ipython-input-22-f9824bcda59a>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df= df.applymap(lambda x: x.strip() if isinstance(x, str) else x)


In [23]:
df.head()

,Age,IsAttrition,Travel_Frequency,Daily_Rate_USD,Department,DistanceFromHome,Education_Level,Field_Of_Study,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,Total_Experience_Years,TrainingTimesLastYear,WorkLifeBalance,Tenure_Years,Current_Role_Years,Years_Since_Promotion,Manager_Years
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Yes,11,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,No,23,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Yes,15,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Yes,11,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,No,12,3,4,1,6,3,3,2,2,2,2


In [26]:
df.skew

<bound method DataFrame.skew of       Age IsAttrition   Travel_Frequency  ...  Current_Role_Years Years_Since_Promotion  Manager_Years
0      41         Yes      Travel_Rarely  ...                   4                     0              5
1      49          No  Travel_Frequently  ...                   7                     1              7
2      37         Yes      Travel_Rarely  ...                   0                     0              0
3      33          No  Travel_Frequently  ...                   7                     3              0
4      27          No      Travel_Rarely  ...                   2                     2              2
...   ...         ...                ...  ...                 ...                   ...            ...
1465   36          No  Travel_Frequently  ...                   2                     0              3
1466   39          No      Travel_Rarely  ...                   7                     1              7
1467   27          No      Travel_Rarely  ...                   2                     0              3
1468   49          No  Travel_Frequently  ...                   6                     0              8
1469   34          No      Travel_Rarely  ...                   3                     1              2

[1470 rows x 31 columns]>

In [44]:
x=df.drop(['IsAttrition'],axis=1)
y=df['IsAttrition']

In [30]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [37]:
le=LabelEncoder()
df['IsAttrition']=le.fit_transform(df['IsAttrition'])
df['Travel_Frequency']=le.fit_transform(df['Travel_Frequency'])
df['Field_Of_Study']=le.fit_transform(df['Field_Of_Study'])
df['Gender']=le.fit_transform(df['Gender'])
df['Department']=le.fit_transform(df['Department'])
df['JobRole']=le.fit_transform(df['JobRole'])
df['MaritalStatus']=le.fit_transform(df['MaritalStatus'])
df['OverTime']=le.fit_transform(df['OverTime'])


In [45]:
x.head()

,Age,Travel_Frequency,Daily_Rate_USD,Department,DistanceFromHome,Education_Level,Field_Of_Study,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,Total_Experience_Years,TrainingTimesLastYear,WorkLifeBalance,Tenure_Years,Current_Role_Years,Years_Since_Promotion,Manager_Years
0,41,2,1102,2,1,2,1,2,0,94,3,2,7,4,2,5993,19479,8,1,11,3,1,0,8,0,1,6,4,0,5
1,49,1,279,1,8,1,1,3,1,61,2,2,6,2,1,5130,24907,1,0,23,4,4,1,10,3,3,10,7,1,7
2,37,2,1373,1,2,2,4,4,1,92,2,1,2,3,2,2090,2396,6,1,15,3,2,0,7,3,3,0,0,0,0
3,33,1,1392,1,3,4,1,4,0,56,3,1,6,3,1,2909,23159,1,1,11,3,3,0,8,3,3,8,7,3,0
4,27,2,591,1,2,1,3,1,1,40,3,1,2,2,1,3468,16632,9,0,12,3,4,1,6,3,3,2,2,2,2


In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [47]:
x_train.shape,y_train.shape

((1176, 30), (1176,))

In [48]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [49]:
re=RandomForestClassifier()
re.fit(x_train,y_train)

RandomForestClassifier()

In [50]:
y_pred=re.predict(x_test)

In [51]:
accuracy_score(y_test,y_pred)

0.8775510204081632

In [52]:
input=(41,2,1102,2,1,2,1,2,0,94,3,2,7,4,2,5993,19479,8,1,11,3,1,0,8,0,1,6,4,0,5)
input_array=np.asarray(input)
input_reshaped=input_array.reshape(1,-1)
predicition=re.predict(input_reshaped)
if predicition[0]==0:
  print('Employee will not leave the company')
else:
  print('Employee will leave the company')


Employee will leave the company


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
