# Numpy  Indexing and Slicing

In [1]:
import numpy as np

In [2]:
# create a array
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
a[0]

1

In [4]:
a[-1]

7

In [5]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [6]:
c = b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [7]:
c[0]

array([0, 2, 4])

In [8]:
c[1]

array([ 6,  8, 10])

In [9]:
c = b.reshape(3,2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [10]:
c[0]

array([0, 2])

In [11]:
c[(c<5) & (c<7)]

array([0, 2, 4])

# enlist boolean operators conditional operators

Here are the main boolean and conditional operators in Python: [1]

# Boolean Operators:

and - Returns True if both statements are true
or - Returns True if one of the statements is true
not - Reverses the boolean value of a single statement

# Conditional Operators:

if/elif/else - Allows you to run certain code blocks based on conditional tests
Comparison Operators (==, !=, >, <, >=, <=) - Compare values and return True or False

# Creating arrays from existing data or another array

In [12]:
a  = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [13]:
len(a)

45

In [14]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [15]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [16]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [17]:
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

----------------------------------------------------------------
# Creating Matrices

In [18]:
# creating a 2x3 matrix (rows, cols)
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# create a matrix of big dimensions
b = np.arange(0, 1000, 2).reshape(5,100)
b

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
         52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
         78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
        104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
        130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
        156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
        182, 184, 186, 188, 190, 192, 194, 196, 198],
       [200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224,
        226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250,
        252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276,
        278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302,
        304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328,
        330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 35

# slicing the matrix

In [39]:
# row , column
b[1:3, 3:5]

array([[206, 208],
       [406, 408]])

In [42]:
b[0:, 1:3]

array([[  2,   4],
       [202, 204],
       [402, 404],
       [602, 604],
       [802, 804]])

In [44]:
b.max()

998

In [45]:
b.min()

0

In [46]:
b.mean()

499.0

In [47]:
b.sum()

249500

In [48]:
# only for columns
b.min(axis=0)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [49]:
# only for rows
b.min(axis=1)

array([  0, 200, 400, 600, 800])

In [56]:
m = np.arange(0,24,2).reshape(6,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22]])

In [58]:
# addition
m + np.array([20,22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40],
       [40, 44]])

In [61]:
m - np.array([20,22])

array([[-20, -20],
       [-16, -16],
       [-12, -12],
       [ -8,  -8],
       [ -4,  -4],
       [  0,   0]])

In [62]:
m % np.array([20,22])

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [ 0,  0]])

In [60]:
np.vstack((m, np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22],
       [42, 44]])