# Pytorch의 nn.Embedding
- Pytorch의 Embedding Layer는 word2vec과 마찬가지로 word embedding vector를 찾는 **Lookup Table**이다.
    - 단어의 **정수의 고유 index**가 입력으로 들어오면 Embedding Layer의 **그 index의 Vector**를 출력한다.
    - 모델이 학습되는 동안 모델이 풀려는 문제에 맞는 값으로 Embedding Layer의 vector들이 업데이트 된다.
    - Word2Vec의 embedding vector 학습을 nn.Embedding은 자신이 포함된 모델을 학습 하는 과정에서 한다고 생각하면 된다.

In [8]:
import torch
import torch.nn as nn

embed = nn.Embedding(
    num_embeddings=20_000,  # vocab size(단어사전의 단어수.) -> 총 몇개의 단어에 대한 embedding vector를 만들지.
    embedding_dim=200,      # embedding vector의 차원수 -> 개별 단어를 몇개의 숫자(feature)로 표현할지.
)

In [9]:
# embed.weight
embed.weight.shape

torch.Size([20000, 200])

In [10]:
# embedding layer의 입력 - 문서를 구성하는 토큰들의 ID(**정수**)를 1차원 묶어서 전달.

# doc = 나는-30 | 어제-159 | 밥을-9000 | 먹었다-326
doc = torch.tensor([[30, 159, 9000, 326], [30, 159, 9000, 326], [30, 159, 9000, 326]], dtype=torch.int64) 
embedding_vector = embed(doc)
embedding_vector.shape

#[1: batch_size, 4:seq_len, 200: embedding vector 차원수]

torch.Size([3, 4, 200])

In [11]:
embedding_vector[0, 0]

tensor([-3.4864e-01, -3.1979e-01,  2.7475e-01,  3.7985e-01, -1.7409e+00,
         8.5567e-01, -2.6771e+00, -5.9154e-01, -1.0054e-01, -2.0596e-01,
        -3.8133e-01, -1.4260e+00, -6.8092e-01,  6.1827e-02,  1.7557e-01,
        -6.1903e-01,  2.3863e-01, -1.0695e+00,  2.0139e-01,  1.2283e+00,
        -1.1054e+00, -9.5198e-01,  3.9925e-01,  2.0405e+00,  2.7226e-02,
        -1.5252e+00,  7.1438e-01, -5.9294e-01, -1.7375e+00,  1.9032e+00,
        -9.7714e-01,  1.0356e+00, -1.0103e+00,  1.4655e+00,  5.0521e-02,
         7.0968e-01, -1.3867e+00, -1.0711e-01,  8.3753e-01,  2.6320e-01,
        -7.2253e-01, -2.1325e-01,  1.0195e-01,  4.2452e-02, -5.7652e-01,
        -1.1171e+00,  5.8908e-01, -3.0008e+00, -1.7802e+00, -5.1621e-01,
         1.2259e+00, -5.3254e-01,  5.2176e-01, -2.3223e+00, -2.0458e-01,
        -8.7639e-02,  2.4311e+00, -6.8423e-01,  2.1702e+00, -1.8045e+00,
        -8.9600e-01, -1.1069e+00,  1.0593e-01,  6.6518e-01,  2.9279e-01,
         7.7602e-01,  1.9075e-02,  3.9959e-01,  1.0

In [12]:
embed.weight[30] # weight가 embedding vector값이다.

tensor([-3.4864e-01, -3.1979e-01,  2.7475e-01,  3.7985e-01, -1.7409e+00,
         8.5567e-01, -2.6771e+00, -5.9154e-01, -1.0054e-01, -2.0596e-01,
        -3.8133e-01, -1.4260e+00, -6.8092e-01,  6.1827e-02,  1.7557e-01,
        -6.1903e-01,  2.3863e-01, -1.0695e+00,  2.0139e-01,  1.2283e+00,
        -1.1054e+00, -9.5198e-01,  3.9925e-01,  2.0405e+00,  2.7226e-02,
        -1.5252e+00,  7.1438e-01, -5.9294e-01, -1.7375e+00,  1.9032e+00,
        -9.7714e-01,  1.0356e+00, -1.0103e+00,  1.4655e+00,  5.0521e-02,
         7.0968e-01, -1.3867e+00, -1.0711e-01,  8.3753e-01,  2.6320e-01,
        -7.2253e-01, -2.1325e-01,  1.0195e-01,  4.2452e-02, -5.7652e-01,
        -1.1171e+00,  5.8908e-01, -3.0008e+00, -1.7802e+00, -5.1621e-01,
         1.2259e+00, -5.3254e-01,  5.2176e-01, -2.3223e+00, -2.0458e-01,
        -8.7639e-02,  2.4311e+00, -6.8423e-01,  2.1702e+00, -1.8045e+00,
        -8.9600e-01, -1.1069e+00,  1.0593e-01,  6.6518e-01,  2.9279e-01,
         7.7602e-01,  1.9075e-02,  3.9959e-01,  1.0

# 네이버 영화 댓글 감성분석(Sentiment Analysis)

## 감성분석(Sentiment Analysis) 이란
입력된 텍스트가 **긍적적인 글**인지 **부정적인**인지 또는 **중립적인** 글인지 분석하는 것을 감성(감정) 분석이라고 한다.   
이를 통해 기업이 고객이 자신들의 기업 또는 제품에 대해 어떤 의견을 가지고 있는지 분석한다.

# Dataset, DataLoader 생성

## Korpora에서 Naver 영화 댓글 dataset 가져오기
- https://ko-nlp.github.io/Korpora/ko-docs/corpuslist/nsmc.html
- http://github.com/e9t/nsmc/
    - input: 영화댓글
    - output: 0(부정적댓글), 1(긍정적댓글)
### API
- **corpus 가져오기**
    - `Korpora.load('nsmc')`
- **text/label 조회**
    - `corpus.get_all_texts()` : 전체 corpus의 text들을 tuple로 반환
    - `corpus.get_all_labels()`: 전체 corpus의 label들을 list로 반환
- **train/test set 나눠서 조회**
    - `corpus.train`
    - `corpus.test`
    - `LabeledSentenceKorpusData` 객체에 text와 label들을 담아서 제공.
        - `LabeledSentenceKorpusData.texts`: text들 tuple로 반환.
        - `LabeledSentenceKorpusData.labels`: label들 list로 반환.

## 데이터 로딩

In [13]:
import os
import time

from Korpora import Korpora

corpus = Korpora.load("nsmc")


    Korpora 는 다른 분들이 연구 목적으로 공유해주신 말뭉치들을
    손쉽게 다운로드, 사용할 수 있는 기능만을 제공합니다.

    말뭉치들을 공유해 주신 분들에게 감사드리며, 각 말뭉치 별 설명과 라이센스를 공유 드립니다.
    해당 말뭉치에 대해 자세히 알고 싶으신 분은 아래의 description 을 참고,
    해당 말뭉치를 연구/상용의 목적으로 이용하실 때에는 아래의 라이센스를 참고해 주시기 바랍니다.

    # Description
    Author : e9t@github
    Repository : https://github.com/e9t/nsmc
    References : www.lucypark.kr/docs/2015-pyconkr/#39

    Naver sentiment movie corpus v1.0
    This is a movie review dataset in the Korean language.
    Reviews were scraped from Naver Movies.

    The dataset construction is based on the method noted in
    [Large movie review dataset][^1] from Maas et al., 2011.

    [^1]: http://ai.stanford.edu/~amaas/data/sentiment/

    # License
    CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
    Details in https://creativecommons.org/publicdomain/zero/1.0/

[Korpora] Corpus `nsmc` is already installed at C:\Users\Playdata\Korpora\nsmc\ratings_train.txt
[Korpora] Corpus `nsmc` is already installed at C:\Users\

In [14]:
all_inputs = corpus.get_all_texts()  # inputs: 댓글들 전체
all_labels = corpus.get_all_labels() # outputs: labels 전체 - 0: 부정, 1: 긍정

In [15]:
all_inputs[:5]

('아 더빙.. 진짜 짜증나네요 목소리',
 '흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나',
 '너무재밓었다그래서보는것을추천한다',
 '교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정',
 '사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 던스트가 너무나도 이뻐보였다')

In [16]:
all_labels[:5]

[0, 1, 0, 0, 1]

In [17]:
len(all_inputs)

200000

In [18]:
corpus.train

NSMC.train: size=150000
  - NSMC.train.texts : list[str]
  - NSMC.train.labels : list[int]

In [19]:
corpus.train.texts

('아 더빙.. 진짜 짜증나네요 목소리',
 '흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나',
 '너무재밓었다그래서보는것을추천한다',
 '교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정',
 '사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 던스트가 너무나도 이뻐보였다',
 '막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화.ㅋㅋㅋ...별반개도 아까움.',
 '원작의 긴장감을 제대로 살려내지못했다.',
 '별 반개도 아깝다 욕나온다 이응경 길용우 연기생활이몇년인지..정말 발로해도 그것보단 낫겟다 납치.감금만반복반복..이드라마는 가족도없다 연기못하는사람만모엿네',
 '액션이 없는데도 재미 있는 몇안되는 영화',
 '왜케 평점이 낮은건데? 꽤 볼만한데.. 헐리우드식 화려함에만 너무 길들여져 있나?',
 '걍인피니트가짱이다.진짜짱이다♥',
 '볼때마다 눈물나서 죽겠다90년대의 향수자극!!허진호는 감성절제멜로의 달인이다~',
 '울면서 손들고 횡단보도 건널때 뛰쳐나올뻔 이범수 연기 드럽게못해',
 '담백하고 깔끔해서 좋다. 신문기사로만 보다 보면 자꾸 잊어버린다. 그들도 사람이었다는 것을.',
 '취향은 존중한다지만 진짜 내생에 극장에서 본 영화중 가장 노잼 노감동임 스토리도 어거지고 감동도 어거지',
 'ㄱ냥 매번 긴장되고 재밋음ㅠㅠ',
 '참 사람들 웃긴게 바스코가 이기면 락스코라고 까고바비가 이기면 아이돌이라고 깐다.그냥 까고싶어서 안달난것처럼 보인다',
 '굿바이 레닌 표절인것은 이해하는데 왜 뒤로 갈수록 재미없어지냐',
 '이건 정말 깨알 캐스팅과 질퍽하지않은 산뜻한 내용구성이 잘 버무러진 깨알일드!!♥',
 '약탈자를 위한 변명, 이라. 저놈들은 착한놈들 절대 아닌걸요.',
 '나름 심오한 뜻도 있는 듯. 그냥 학생이 선생과 놀아나는 영화는 절대 아님',
 '보면서 웃지 않는 건 불가능하다',
 '재미없다 지루하고. 같은 음식 영화인데도 바베트의 만찬하고 넘 차이남....바베트의 만찬은 이야기도 있

In [20]:
corpus.test

NSMC.test: size=50000
  - NSMC.test.texts : list[str]
  - NSMC.test.labels : list[int]

In [21]:
corpus.test.texts[:5]

('굳 ㅋ',
 'GDNTOPCLASSINTHECLUB',
 '뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아',
 '지루하지는 않은데 완전 막장임... 돈주고 보기에는....',
 '3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??')

In [22]:
corpus.test.labels[:5]

[1, 0, 0, 0, 0]

## 토큰화 (전처리 개념)
1. 형태소 단위 token화(분절)를 먼저 한다.
    - konlpy로 token화 한 뒤 다시 한 문장으로 만든다.
2. 1에서 처리한 corpus를 BPE 로 token화
   
### 전처리 함수

#### 형태소 단위 분절

In [23]:
import string
list(string.punctuation)

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [24]:
# 전처리 = cleansing + 정규화(normalize)
from konlpy.tag import Okt
import string
import re

okt = Okt()
def text_preprocessing(text):
    """
    1. 영문 -> 소문자로 변환 # 대소문자 통일도 정규화 작업중 하나!
    2. 구두점 제거
    3. 형태소 기반 토큰화
    4. 형태소로 토큰화 한 뒤 다시 하나의 문자열로 묶어서 반환.
    """
    text = text.lower()
    # 구두점 제거 (stop word(불용어))
    text = re.sub(f"[{string.punctuation}]", " ", text)
    # 정규화
    tokens = okt.morphs(text, stem=True) # stem: 원형복원. norm=True (비속어 제외)
    return ' '.join(tokens) # ["단어", "단어", ..] -> str "단어 단어 단어"
    

In [25]:
print(all_inputs[101])
text_preprocessing(all_inputs[101])


재미없음 진심 1이훨나 캐스팅두못한듯


'재미없다 진심 1 이훨 나 캐스팅 두 못 한 듯'

In [26]:
s = time.time()
# train set 전처리
train_texts = corpus.train.texts
train_inputs = [text_preprocessing(txt) for txt in train_texts]
train_labels = corpus.train.labels

# test set 전처리
test_texts = corpus.test.texts
test_inputs = [text_preprocessing(txt) for txt in test_texts]
test_labels = corpus.test.labels
e = time.time()

print('전처리 걸린시간(초):', e-s) 

전처리 걸린시간(초): 352.67093324661255


In [27]:
import pickle
import os

os.makedirs("datasets/nsmc", exist_ok=True)
with open("datasets/nsmc/preprocessing_trainset.pkl", "wb") as fw:
    pickle.dump({"input":train_inputs, "output": train_labels}, fw)

In [28]:
with open("datasets/nsmc/preprocessing_testset.pkl", "wb") as fw:
    pickle.dump({"input": test_inputs, "output":test_labels}, fw)

In [32]:
# pickle로 저장한 전처리한 데이터셋 읽어 오기.
import pickle
with open("datasets/nsmc/preprocessing_trainset.pkl", "rb") as fr:
    train_dict = pickle.load(fr)

with open("datasets/nsmc/preprocessing_testset.pkl", "rb") as fr:
    test_dict = pickle.load(fr)

In [33]:
train_inputs = train_dict['input']
train_labels = train_dict['output']

test_inputs = test_dict['input']
test_labels = test_dict['output']


In [34]:
all_inputs = train_inputs + test_inputs # vocab 만들때 사용.

In [35]:
len(train_inputs), len(test_inputs), len(all_inputs)

(150000, 50000, 200000)

### 토큰화
- Subword 방식 토큰화 적용
- Byte Pair Encoding 방식으로 huggingface tokenizer 사용
    - BPE: 토큰을 글자 단위로 나눈뒤 가장 자주 등장하는 글자 쌍(byte paire)를 찾아 합친뒤 어휘사전에 추가한다.
    - https://huggingface.co/docs/tokenizers/quicktour
    - `pip install tokenizers`

In [37]:
from tokenizers import Tokenizer
from tokenizers.models import BPE #, Unigram, WordPiece
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.trainers import BpeTrainer

vocab_size = 30_000 # 최대 어휘사전에 최대 단어수
min_frequency = 5   # 사전에 추가할 최소 빈도 수.

tokenizer = Tokenizer(
    BPE(unk_token="[UNK]")
)
tokenizer.pre_tokenizer = Whitespace()
trainer = BpeTrainer(
    vocab_size=vocab_size,
    min_frequency=min_frequency,
    special_tokens=["[PAD]", "[UNK]"],
    continuing_subword_prefix="##" # 단어의 중간에 나오는 subword일 경우 앞에 ##을 붙인다.
    #"시작하는" -> "시작", "하는" => "시작", "##하는"
)
tokenizer.train_from_iterator(all_inputs, trainer=trainer) # vocab 생성 == tokenizer학습.

In [ ]:
tokenizer.token_to_id("[PAD]")

0

In [ ]:
# 총 vocab size:
tokenizer.get_vocab_size()

26738

In [ ]:
# 저장
os.makedirs("saved_models/nsmc", exist_ok=True)
tokenizer.save("saved_models/nsmc/tokenizer_bpe.json")

# load_tokenizer = Tokenizer.from_file("saved_models/nsmc/tokenizer_bpe.json")

In [ ]:
idx = 11290
print(all_inputs[idx])
tokens = tokenizer.encode(all_inputs[idx])
print(tokens.ids)
print(tokens.tokens)

명작 을 기억 하다 이렇다 드라마 가 또 다시 나오다 있다
[5530, 2190, 5548, 5411, 5455, 5448, 506, 1152, 5486, 5440, 5415]
['명작', '을', '기억', '하다', '이렇다', '드라마', '가', '또', '다시', '나오다', '있다']


In [38]:
e = tokenizer.encode("pytorch와 pandas와 numpy는 python 라이브러리 입니다.")
e.tokens

['p',
 '##y',
 '##t',
 '##or',
 '##ch',
 '##와',
 'p',
 '##and',
 '##as',
 '##와',
 'n',
 '##um',
 '##p',
 '##y',
 '##는',
 'p',
 '##y',
 '##th',
 '##on',
 '라이브',
 '##러리',
 '입',
 '##니다',
 '[UNK]']

In [39]:
tokenizer.decode(e.ids)

'p ##y ##t ##or ##ch ##와 p ##and ##as ##와 n ##um ##p ##y ##는 p ##y ##th ##on 라이브 ##러리 입 ##니다'

In [ ]:
tokenizer.decode(tokens.ids)

'명작 을 기억 하다 이렇다 드라마 가 또 다시 나오다 있다'

## Dataset, DataLoader 생성

In [ ]:
# dset[0]
tokenizer.encode(train_inputs[0]).ids, train_labels[0]

([1986, 5881, 5426, 5667, 6087], 0)

In [ ]:
# Pytorch 사용자 정의 Dataset(Custom Dataset) 정의
# 1. Dataset 상속
# 2. __len__(self) : 총 데이터의 개수 반환
# 3. __getitem__(self, index) : index의 x,y를 반환. - 객체[index]

In [ ]:
train_inputs

['아 더빙 진짜 짜증나다 목소리',
 '흠 포스터 보고 초딩 영화 줄 오버 연기 조차 가볍다 않다',
 '너 무재 밓었 다그 래서 보다 추천 한 다',
 '교도소 이야기 구먼 솔직하다 재미 는 없다 평점 조정',
 '사이 몬페 그 의 익살스럽다 연기 가 돋보이다 영화 스파이더맨 에서 늙다 보이다 하다 커스틴 던스트 가 너무나도 이쁘다 보이다',
 '막 걸음 마 떼다 3 세 부터 초등학교 1 학년 생인 8 살다 영화 ㅋㅋㅋ 별 반개 도 아깝다 움',
 '원작 의 긴장감 을 제대로 살리다 하다',
 '별 반개 도 아깝다 욕 나오다 이응경 길용우 연 기 생활 이 몇 년 인지 정말 발 로 해도 그것 보단 낫다 납치 감금 만 반복 반복 이 드라마 는 가족 도 없다 연기 못 하다 사람 만 모 엿 네',
 '액션 이 없다 재미 있다 몇 안되다 영화',
 '왜케 평점 이 낮다 꽤 볼 만 한 데 헐리우드 식 화려하다 너무 길들이다 있다',
 '걍 인피니트 가 짱 이다 진짜 짱 이다 ♥',
 '볼때 마다 눈물나다 죽다 90년 대의 향수 자극 허진호 는 감성 절제 멜로 의 달인 이다',
 '울면 서 손 들 고 횡단보도 건너다 때 뛰다 치다 올 뻔 이범수 연기 드럽다 못 하다',
 '담백하다 깔끔하다 좋다 신 문 기 사 로만 보다 보다 자꾸 잊어버리다 그 들 도 사람 이다 것 을',
 '취향 은 존중 한 다지 만 진짜 내생 에 극장 에서 보다 영화 중 가장 노잼 노 감동 임 스토리 도 어거지 고 감동 도 어거지',
 'ㄱ 냥 매번 긴장 되다 재밋음 ㅠㅠ',
 '차다 사람 들 웃기다 바스코 가 이기 면 락스 코 라고 끄다 바비 가 이기 면 아이돌 이라고 깔다 그냥 끄다 안달 난 것 처럼 보이다',
 '굿바이 레닌 표절 인 것 은 이해 하다 왜 뒤 로 갈수록 재미 없어지다',
 '이건 정말 깨알 캐스팅 과 질퍽 하 지 않다 산뜻하다 내 용구성 이 자다 버무러진 깨알 일드 ♥',
 '약탈 자 를 위 한 변명 이르다 저 놈 들 은 착하다 놈 들 절대 아니다 걸 요',
 '나름 심오하다 

In [ ]:
train_labels
[tokenizer.encode(txt).ids for txt in train_inputs[:4]]

[[1986, 5881, 5426, 5667, 6087],
 [3034, 5891, 5453, 6036, 5408, 2339, 6775, 5434, 6276, 6134, 5435],
 [839, 8408, 1478, 3100, 11369, 13191, 5410, 5634, 2889, 950],
 [12558, 5519, 16061, 5633, 5418, 923, 5412, 5441, 8922]]

In [ ]:
tokenizer.token_to_id

<function Tokenizer.token_to_id(self, token)>

In [ ]:
tokenizer.token_to_id("[PAD]")

0

In [40]:
for txt in train_inputs:
    print(tokenizer.encode(txt))
    break

Encoding(num_tokens=5, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])


In [161]:
import torch
from torch.utils.data import Dataset, DataLoader

class NSMCDataset(Dataset):
    def __init__(self, texts, labels, max_length, tokenizer):
        """
        texts: list - 댓글 목록. 리스트에 댓글들을 담아서 받는다. ["댓글", "댓글", ...]
        labels: list - 댓글 Label(긍/부정) 목록. 
        max_length: 개별 댓글의 최대 token 개수. 모든 댓글의 토큰수를 max_length에 맞춘다.
        tokenizer: Tokenizer
        """
        self.max_length = max_length
        self.tokenizer = tokenizer
        self.labels = labels
        # self.texxts: 입력댓글 - token id로 변환된 댓글(문서). 글자수는 max_length에 맞춤.
        #              max_length  보다 적으면 [PAD] 추가, max_length보다 많으면 잘라낸다.
        self.texts = [self.__pad_token_sequences(tokenizer.encode(txt).ids) for txt in texts]

    ###########################################################################################
    # id로 구성된 개별 문장 token list를 받아서 패딩 추가 [20, 2, 1] => [20, 2, 1, 0, 0, 0, ..]
    # max_length에 토큰 리스트의 개수를 맞춰주는 함수.
    ############################################################################################
    def __pad_token_sequences(self, token_sequences): # 앞에 __ 붙이면 class안에서만 사용하겠다.밖에서는 적용 안됨. (JAVA에서는 private)
        """
        id로 구성된 개별 문서(댓글)의 token_id list를 받아서 max_length 길이에 맞추는 메소드
        max_length 보다 토큰수가 적으면 [PAD] 추가, 많으면 max_length 크기로 줄인다.
            ex) max_length = 5, [PAD] token id가 0
            - [20, 2, 1] => [20, 2, 1, 0, 0]
            - [20, 30, 40, 50, 60, 70, 80] -> [20, 30, 40, 50, 60]
        """
        pad_token_id = self.tokenizer.token_to_id("[PAD]")
        seq_len = len(token_sequences) # 입력받은 토큰 개수.
        result = None
        if seq_len > self.max_length: #잘라내기
            result = token_sequences[:self.max_length]
        else:
            result = token_sequences + ([pad_token_id] * (self.max_length - seq_len))
        
        return result
        
    def __len__(self):
        return len(self.labels) # 총 데이터 개수를 반환.

    def __getitem__(self, idx):
        """
        idx 번째 text와 label을 학습 가능한 type으로 변환해서 반환
        Parameter
            idx: int 조회할 index
        Return
            tuple: (torch.LongTensor, torch.FloatTensor) - 댓글 토큰_id 리스트, 정답 Label
        """
        txt = self.texts[idx]
        label = self.labels[idx]

        return (torch.tensor(txt, dtype=torch.int64), torch.tensor([label], dtype=torch.float32))
    

In [162]:
# 모든 댓글의 토큰수를 조회.
all_input_length = [ len(tokenizer.encode(txt)) for txt in all_inputs]
all_input_length[:5]

[5, 11, 10, 9, 22]

In [163]:
import numpy as np
np.min(all_input_length), np.max(all_input_length)

(0, 89)

In [164]:
np.quantile(all_input_length, q=[0.9, 0.95])
# 전체 중 90%의 토큰수는 29개 미만, 95%는 41개 미만.

array([29., 41.])

In [165]:
200000 * 0.9

180000.0

In [166]:
MAX_LENGTH = 30
trainset = NSMCDataset(train_inputs, train_labels, MAX_LENGTH, tokenizer)
testset = NSMCDataset(test_inputs, test_labels, MAX_LENGTH, tokenizer)

In [167]:
len(trainset), len(testset)

(150000, 50000)

In [168]:
# trainset[0]
trainset[10]

(tensor([  540, 11354,   506,  2408,  5414,  5426,  2408,  5414,   119,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]),
 tensor([1.]))

In [169]:
BATCH_SIZE = 64
train_loader = DataLoader(trainset, batch_size=BATCH_SIZE, shuffle=True, drop_last=True)
test_loader = DataLoader(testset, batch_size=BATCH_SIZE)

In [170]:
len(train_loader), len(test_loader)

(2343, 782)

In [171]:
import torch
import torch.nn as nn

# 어휘사전 어휘수 : 10개
# 임베딩 벡터 차원수 : 3차원

e_layer = nn.Embedding(
    num_embeddings=10,
    embedding_dim=3,
)
# 10 X 3 행렬을 생성 -> weight 행렬이 전체 어휘들의 embedding vector들

In [172]:
e_layer.weight

Parameter containing:
tensor([[-0.6422,  0.7206, -1.0144],
        [ 0.5535,  1.3740, -0.7712],
        [ 1.0521, -1.2421, -0.1125],
        [-0.7502, -1.9998,  0.6224],
        [ 0.8828,  0.1316,  0.7495],
        [-0.0963, -0.5072, -1.8711],
        [-0.6380, -0.5182,  0.3797],
        [ 1.0039,  1.4233,  1.2292],
        [-1.0935, -0.4904,  0.1304],
        [-0.3250, -0.8300,  0.6883]], requires_grad=True)

In [173]:
sent = "오늘 날씨 좋다" # ["오늘", "날씨", "좋다"]
# token = tokenizer.encode(sent).ids
token= torch.tensor([0, 4, 2], dtype=torch.int64) # .ids로 확인하면 어휘사전에 등록된 번호로 출력.
e_layer(token)
'''
[
[-0.4482, -0.5812, -1.2675], <- 0 :오늘
[-1.0349, -0.9678,  0.9191], <- 4 :날씨
[-0.1923, -0.7232, -0.0848]  <- 2 :좋다
]
'''

'\n[\n[-0.4482, -0.5812, -1.2675], <- 0 :오늘\n[-1.0349, -0.9678,  0.9191], <- 4 :날씨\n[-0.1923, -0.7232, -0.0848]  <- 2 :좋다\n]\n'

# 모델링
- Embedding Layer를 이용해 Word Embedding Vector를 추출한다.
- LSTM을 이용해 Feature 추출
- Linear + Sigmoid로 댓글 긍정일 확률 출력
  
![outline](figures/rnn/RNN_outline.png)

- 전체 입력된 것에 대한 파라미터 값을 계산하므로 마지막 hidden state값을 넣어줌.

## 모델 정의

In [174]:
!pip install torchinfo

In [175]:
import torch
import torch.nn as nn
from torchinfo import summary # 모델 정보(summary) 확인 라이브러리
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu


In [176]:
# 모델정의
class NSMCClassifier(nn.Module):

    def __init__(self, vocab_size, embedding_dim, hidden_size, num_layers, bidirectional=True, dropout_rate=0.2):
        """
        Args:
            vocab_size(int) - 어휘사전의 총 어휘수
            embedding_dim - embedding vector의 차원수
            hidden_size(int) - LSTM의 hidden state의 featrue수
            num_layers(int) - LSTM의 layers의 개수
            bidirectional(bool) - LSTM의 양방향 여부
            dropout_rate(float) - LSTM이 두개 이상의 layer로 구성된 경우 적용할 dropout 비율. Dropout Layer의 dropout 비율.
        """
        super().__init__()
        # 모델을 구성할 Layer들을 정의 - Embedding, LSTM, Dropout, Linear(추론기). Sigmoid
        self.embedding = nn.Embedding(
            num_embeddings=vocab_size,   # 총 단어(토큰)수 -> tokenizer에 등록된 총 단어수.
            embedding_dim=embedding_dim, # 임베딩 벡텉의 차원수.
            padding_idx=0                # [PAD]의 토큰 ID(tokenizer.token_to_index("[PAD]"))
                                         # 이렇게 지정하면 padding토큰은 학습하지 않는다. 학습용이 아니라 채우는 용이기 떄문
        )
        # embedding layer의 출력 shape: (batch_size:64, seq_length: 문서 토큰수, embedding_dim(embedding 차원수))

        self.lstm = nn.LSTM(
            input_size=embedding_dim,  # 개별 토큰(단어)의 feature 수 (embedding layer -> LSTM으로 넘어감.)
            hidden_size=hidden_size,
            num_layers=num_layers,
            bidirectional=bidirectional, 
            dropout=dropout_rate if num_layers > 1 else 0, # stacked rnn일 경우 설정.
        )

        self.dropout = nn.Dropout(dropout_rate) # LSTM과 Linear 사이에 과적합 방지를 위해서 사용.

        # lstm의 출력 :  out, (hidden, cell)
        # out : 모든 타임스탭의 hidden state값 - [seq_len, batch, hidden_size * bidirectional여부(0,1)]
        # hidden : 마지막 타입스탭의 hidden state값 (단기기억값) -[bidirectinal * num_layer(개수), batch, hidden]
        # cell : 마지막 타임슽탭의 cell state값 (장기기억값)

        input_features = hidden_size*2 if bidirectional else hidden_size
        self.classifier = nn.Linear(input_features, 1) # 출력 1 : 이진분류 -> positive의 확률.
        self.sigmoid = nn.Sigmoid()        # classifier의 출력값을 확률(0 ~ 1) 값으로 변환하는 함수.

    def forward(self, X):
        """
        Args
            X(tensor): 입력 문서 토큰 리스트. shape: [batch_size, seq_length(max_length : 문서 구성 토큰수)] - [64, 30]
        """
        embedding_vectors = self.embedding(X)
        # [batch, seq_len] -> embedding -> [batch, seq_len, embedding_dim (embedding_차원수)]
        # LSTM - batch_first = False : 입력 shape - [seq_len, batch_size, embedding_dim]
        # embedding_vector의 batch 축과 seq_len 축(값의 위치 = 값의 index)을 바꿔준다.
        embedding_vectors = embedding_vectors.transpose(1, 0) # transpose() : 딱 두개의 축의 값의 위치만 바꿔줄 때 사용.
        out, _ = self.lstm(embedding_vectors)
        # out.shape: [seq_len, batch, hidden_size * (2 if bidirectional else 1)]
        # classifier(linear)에는 out의 마지막 index(마지막 seq) 값을 입력.
        output = self.dropout(out[-1])
        output = self.classifier(output)
        
        last_output = self.sigmoid(output)
        return last_output

In [177]:
# ev.transpose(1, 0)
# # 파라미터의 순서 : index를 이동시킬 축 위치
# # 파라미터 값 : 이동할 대상 index의 축 위치
# # 1 -> 0, 0 -> 1

# ev = [
#     [10, 20, 30],
#     [40, 50, 60]
# ] # shape: (2, 3)
# a = ev.transpose(1, 0)
# 10 idx : [0, 0] -> [0, 0] # 바꿔도 0, 0
# 20 idx : [0, 1] -> [1, 0]
# 30 idx : [0, 2] -> [2, 0]
# 40 idx : [1, 0] -> [0, 1]

# a[
#     [10, 40],
#     [20, 50],
#     [30, 60],
# ] # transpose 이후엔 shape이 (3, 2)로 바뀜. transpose ->  값의 위치를 바꾸는 것. reshape의 기능과 완전히 다름.

# b = a.reshape(3, 2)
# [ 
#     [10, 20],
#     [30, 40],
#     [50, 60]
# ]

In [178]:
# [20, 50, 8, 0, 0] -> embedding layer ->[[0.1,0.2,,0.3], [1.2, 0.2, -1.2], [], [], []]  (1,5,3)

In [179]:
# tokenizer.encode("이 영화 정말 재미있다.").ids

## 모델 생성

In [180]:
VOCAB_SIZE = tokenizer.get_vocab_size() # 총 어휘수
EMBEDDING_DIM = 100
HIDDEN_SIZE = 64
NUM_LAYERS = 2
BIDIRECTIONAL=True # 양방향
DROPOUT_RATE = 0.3

# 모델의 복잡도를 올린다. => EMBEDDING_DIM, HIDDEN_SIZE, NUM_LAYERS를 크게 잡기.
# Auto regressive 모델이 아니면 => BIDIRECTIONAL=True(양방향)

model = NSMCClassifier(
    vocab_size=VOCAB_SIZE,
    embedding_dim=EMBEDDING_DIM,
    hidden_size=HIDDEN_SIZE,
    num_layers=NUM_LAYERS,
    bidirectional=BIDIRECTIONAL,
    dropout_rate=DROPOUT_RATE
)
model = model.to(device)
print(model)

NSMCClassifier(
  (embedding): Embedding(26744, 100, padding_idx=0)
  (lstm): LSTM(100, 64, num_layers=2, dropout=0.3, bidirectional=True)
  (dropout): Dropout(p=0.3, inplace=False)
  (classifier): Linear(in_features=128, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


In [181]:
# summary로 모델 확인
i = torch.randint(1, 10, (64, MAX_LENGTH)) # int 64 타입의 dummy 입력 데이터. 
# 입력 shape : (batch, seq_len)
summary(model, input_data=i, device=device)
# summary(모델, input_shape) => 내부적으로 입력데이이터(float32)를 생성해서 추론.

Layer (type:depth-idx)                   Output Shape              Param #
NSMCClassifier                           [64, 1]                   --
├─Embedding: 1-1                         [64, 30, 100]             2,674,400
├─LSTM: 1-2                              [30, 64, 128]             184,320
├─Dropout: 1-3                           [64, 128]                 --
├─Linear: 1-4                            [64, 1]                   129
├─Sigmoid: 1-5                           [64, 1]                   --
Total params: 2,858,849
Trainable params: 2,858,849
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 525.06
Input size (MB): 0.02
Forward/backward pass size (MB): 3.50
Params size (MB): 11.44
Estimated Total Size (MB): 14.95

## 학습

### Train/Test 함수 정의

In [182]:
# 1 epoch train 하는 함수.
def train(model, dataloader, loss_fn, optimizer, device="cpu"):
    # 1. 모델을 train 하는 모드로 변환.
    model.train()
    # 2. 모델을 device로 이동
    model = model.to(device)
    total_loss = 0.0 # step별 loss를 저장.
    # step 단위로 모델 학습 ( batch )
    for X, y in dataloader:
        # 1. X, y를 device로 이동
        X, y = X.to(device), y.to(device)
        # 2. 추론
        pred = model(X)
        # 3. loss 계산
        loss = loss_fn(pred, y) # 여기까지가 순전파
        # 4. gradient 계산
        loss.backward()
        # 5. 파라미터 업데이트 : w.data - w.grad * lr
        optimizer.step()
        # 6. gradient 초기화
        optimizer.zero_grad()
        # 7. loss 누적
        total_loss += loss.item()
    # 1 epoch 학습 완료
    return total_loss / len(dataloader) # 1 epoch의 train loss를 반환. (total loss / step수수)

In [183]:
# 1 epoch 평가/검증 함수
def test(model, dataloader, loss_fn, device="cpu"):
    # 1. 모델을 eval 모드로 변경, model을 device로 이동
    model.eval()
    model = model.to(device)
    # loss, accuracy 확인
    total_loss = 0.0
    total_acc = 0.0
    with torch.no_grad(): # 순전파 시 gradient 함수는 만들지 말아라.
        for X, y in dataloader:
            # 1. step 처리.
            # 1. X, y를 device로 이동
            X, y = X.to(device), y.to(device)
          
            # 2. 추론
            pred_proba = model(X) # 양성일 확률
            pred_label = (pred_proba > 0.5).type(torch.int32) # True, False를 1,0으로 출력되게 해줌.
            total_loss += loss_fn(pred_proba, y).item()
            total_acc += (pred_label == y).sum().item() # T, F로 나오는 것들을 int형태로 합함.
        
        # return loss, acc
        return total_loss / len(dataloader), total_acc / len(dataloader.dataset)
    # pred_proba = 1 if [0.7, 0.2, 0.6] > thresh else 0

### Train

In [184]:
LR = 0.0001
EPOCHS = 3
loss_fn = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LR)

In [185]:
import time

s = time.time()
train_loss_list = []
val_loss_list = []
val_acc_list = []

for epoch in range(EPOCHS):
    train_loss = train(model, train_loader, loss_fn, optimizer, device)
    val_loss, val_acc = test(model, test_loader, loss_fn, device)
    train_loss_list.append(train_loss)
    val_loss_list.append(val_loss)
    val_acc_list.append(val_acc)
    print(f"[{epoch}/{EPOCHS}] train loss: {train_loss}, val loss: {val_loss}, val acc: {val_acc}")
e = time.time()
print(e-s)

[0/3] train loss: 0.6549141088129362, val loss: 0.5008755821706085, val acc: 0.7595
[1/3] train loss: 0.4513811616754104, val loss: 0.42437163776601367, val acc: 0.80164
[2/3] train loss: 0.39875979357761954, val loss: 0.4081833925088653, val acc: 0.81296
617.1224927902222


In [134]:
# next(iter(train_loader))[1].shape

<!-- ## 모델저장 -->

## 모델 저장

In [94]:
torch.save(model, 'saved_models/nsmc/model.pt')

In [95]:
#모델로드
load_model = torch.load('saved_models/nsmc/model.pt', weights_only=False)

# 서비스

## 전처리 함수들

In [186]:
from konlpy.tag import Okt

morph_tokenizer = Okt()

def text_preprocessing(text):
    
    text = text.lower()
    text = re.sub(f"[{string.punctuation}]+", ' ', text)
    return ' '.join(morph_tokenizer.morphs(text, stem=True)) # stem = True : normalization

In [187]:
def pad_token_sequences(token_sequences, max_length):
    """padding 처리 메소드."""
    pad_token = tokenizer.token_to_id('[PAD]')  
    seq_length = len(token_sequences)           
    result = None
    if seq_length > max_length:                 
        result = token_sequences[:max_length]
    else:                                            
        result = token_sequences + ([pad_token] * (max_length - seq_length))
    return result

In [188]:
def predict_data_preprocessing(text_list):
    """
    모델에 입력할 수있는 input data를 생성
    Parameter:
        text_list: list - 추론할 댓글리스트
    Return
        torch.LongTensor - 댓글 token_id tensor
    """
   
    #cleansing + 정규화
    text_list = [text_preprocessing(txt) for txt in text_list]
    # text -> 토큰화
    token_list = [tokenizer.encode(txt).ids for txt in text_list]
    # 토큰 리스트의 크기(size)를  max_length에 맞추기
    token_list = [pad_token_sequences(token, MAX_LENGTH) for token in token_list]
    return torch.tensor(token_list, dtype=torch.int64)

## 추론

In [189]:
text_preprocessing("이걸 영화라고 만들었냐?")

'이 걸 영화 라고 만들다'

In [190]:
comment_list = ["아 진짜 재미없다.", "여기 식당 먹을만 해요", "이걸 영화라고 만들었냐?", "기대 안하고 봐서 그런지 괜찮은데.", "이걸 영화라고 만들었나?", "아! 뭐야 진짜.", "재미있는데.", "연기 짱 좋아. 한번 더 볼 의향도 있다.", "뭐 그럭저럭"]
input_tensor = predict_data_preprocessing(comment_list)
input_tensor.shape

torch.Size([9, 30])

In [191]:
input_tensor

tensor([[ 1986,  5426,  5471,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [ 5940, 11676,  5561,  2907,  2128,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [ 2206,   548,  5408,  5545,  5439,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [ 5517,  1988,  5470,  5410,  5482,  5549,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0],
        [ 2206,   548,  5408,  5545,  5439,     

In [195]:
def predict(model, comment_list:list[str], input_tensor:torch.tensor, device='cpu'):
    """
    model로 comment_list(토큰 id로 변환된 tensor)를 추론해서 긍정/부정적인 댓글인지 출력.
    출력 형식
        comment(댓글) label 확률
        "아 재미없다."  부정  0.9    (부정적인 댓글일 확률)
        "재밌다."       긍정 0.87   (긍정적인 댓글일 확률률)
     """
    model.eval() # 평가모드로 전환
    model = model.to(device)
    with torch.no_grad():
        pred = model(input_tensor) # shape: (batch, 1) -> positive 일 확률
        for txt, pos_proba in zip(comment_list, pred):
            label = "긍정적" if pos_proba.item() > 0.5 else "부정적" # 0.5 -> threshold
            proba = pos_proba.item() if pos_proba.item() > 0.5 else 1-pos_proba.item() #확률
            print(txt, label, round(proba, 3), sep='\t')


In [196]:
predict(model, comment_list, input_tensor, device)

아 진짜 재미없다.	부정적	0.979
여기 식당 먹을만 해요	부정적	0.621
이걸 영화라고 만들었냐?	부정적	0.978
기대 안하고 봐서 그런지 괜찮은데.	긍정적	0.813
이걸 영화라고 만들었나?	부정적	0.978
아! 뭐야 진짜.	부정적	0.908
재미있는데.	긍정적	0.961
연기 짱 좋아. 한번 더 볼 의향도 있다.	긍정적	0.937
뭐 그럭저럭	부정적	0.955


In [160]:
print("분석하려는 댓글을 입력하세요. 종료하려면 'quit'을 입력하세요")
while True:
    comment = input("댓글:")
    if comment == "quit":
        print('종료')
        break
    comment_list = [comment]
    input_tensor = predict_data_preprocessing([comment])
    predict(model, comment_list, input_tensor, device)

분석하려는 댓글을 입력하세요. 종료하려면 'quit'을 입력하세요
이걸	부정적	0.513
영화라고	부정적	0.513
만들었냐?	부정적	0.513
종료
