In [1]:
!pip install pandas

  Using cached pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
  Using cached pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
Using cached pytz-2025.1-py2.py3-none-any.whl (507 kB)
Using cached tzdata-2025.1-py2.py3-none-any.whl (346 kB)


In [2]:
import pandas as pd 
df=pd.read_csv("all_kindle_review.csv")

In [3]:
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000


In [4]:
df=df[['reviewText','rating']]

In [5]:
df

,reviewText,rating
0,"Jace Rankin may be short, but he's nothing to ...",3
1,Great short read. I didn't want to put it dow...,5
2,I'll start by saying this is the first of four...,3
3,Aggie is Angela Lansbury who carries pocketboo...,3
4,I did not expect this type of book to be in li...,4
...,...,...
11995,Valentine cupid is a vampire- Jena and Ian ano...,4
11996,I have read all seven books in this series. Ap...,5
11997,This book really just wasn't my cuppa. The si...,3
11998,"tried to use it to charge my kindle, it didn't...",1


In [6]:
df.shape

(12000, 2)

In [7]:
## Missing Values
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [8]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [9]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [10]:
## Preprocessing and cleaning
## Positive review is 1 and Negetive review is 0
df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)

In [11]:
df['rating'].unique()

array([1, 0])

In [12]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [13]:
## Lower all the cases
df['reviewText'] = df['reviewText'].str.lower()

In [14]:
df.head()

,reviewText,rating
0,"jace rankin may be short, but he's nothing to ...",1
1,great short read. i didn't want to put it dow...,1
2,i'll start by saying this is the first of four...,1
3,aggie is angela lansbury who carries pocketboo...,1
4,i did not expect this type of book to be in li...,1


In [15]:
!pip install nltk

  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Using cached nltk-3.9.1-py3-none-any.whl (1.5 MB)
Using cached regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (781 kB)
Using cached click-8.1.8-py3-none-any.whl (98 kB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)


In [16]:
import re
import nltk
from nltk.corpus import stopwords

# Download stopwords if not already available
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))  # Load English stopwords

def clean_text(text):
    # 1. Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)  
    
    # 2. Remove HTML Tags
    text = re.sub(r'<.*?>', '', text)  
    
    # 3. Remove Special Characters (but keep spaces)
    text = re.sub(r'[^a-z A-Z 0-9\s]', '', text)  
    
    # 4. Remove Stopwords
    text = " ".join([word for word in text.split() if word.lower() not in stop_words])
    
    # 5. Remove Extra Spaces
    text = re.sub(r'\s+', ' ', text).strip()  
    
    return text

# Apply the function to the DataFrame
df['reviewText'] = df['reviewText'].apply(clean_text)


[nltk_data] Downloading package stopwords to /home/adarsh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [17]:
df.head()

,reviewText,rating
0,jace rankin may short hes nothing mess man hau...,1
1,great short read didnt want put read one sitti...,1
2,ill start saying first four books wasnt expect...,1
3,aggie angela lansbury carries pocketbooks inst...,1
4,expect type book library pleased find price right,1


In [18]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /home/adarsh/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [19]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer

In [20]:
lemmatizer=WordNetLemmatizer()

In [21]:
def lemmatize_word(text):
  return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [22]:
df['reviewText'] = df['reviewText'].apply(lambda x:lemmatize_word(x))

In [23]:
!pip install scikit-learn

  Using cached scikit_learn-1.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)


In [24]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df['reviewText'],df['rating'],test_size=0.2)

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [27]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [28]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow,Y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tfidf,Y_train)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [30]:
y_pred_bow = nb_model_bow.predict(X_test_bow)
y_pred_tfidf = nb_model_tfidf.predict(X_test_tfidf)

In [31]:
print(accuracy_score(Y_test,y_pred_bow))

0.5779166666666666


In [32]:
print(accuracy_score(Y_test,y_pred_tfidf))

0.5729166666666666


In [33]:
print(confusion_matrix(Y_test,y_pred_bow))

[[485 293]
 [720 902]]


In [34]:
!pip install gensim

In [36]:
from gensim.models import Word2Vec
import numpy as np

# Train Word2Vec model on X_train
word2vec_model = Word2Vec(sentences=X_train, vector_size=100, window=5, min_count=1, workers=4)

# Function to convert sentences to word embeddings (average of word vectors)
def sentence_to_vec(text, model):
    vectors = [model.wv[word] for word in text if word in model.wv]
    return sum(vectors) / len(vectors) if vectors else np.zeros(model.vector_size)

# Convert X_train and X_test into Word2Vec embeddings
X_train_w2v = np.array([sentence_to_vec(sentence, word2vec_model) for sentence in X_train])
X_test_w2v = np.array([sentence_to_vec(sentence, word2vec_model) for sentence in X_test])


In [37]:
nb_model_w2v = GaussianNB().fit(X_train_w2v,Y_train)

In [39]:
y_pred_w2v=nb_model_w2v.predict(X_test_w2v)

In [40]:
print(accuracy_score(Y_test,y_pred_w2v))

0.6229166666666667
