DATA ENCODING

In [1]:
#data encoding>>converting cateegorical columns into numerical columns 

#Nominal/OHE
#Label and ordinal encoding
#TYarget guided ordinal encoding

In [2]:
#Nomibnal/OHE >> Binary vector for each of the category
#example : single , married, separated
#single: [1, 0, 0]
#married: [0, 1, 0]
##separated: [0, 0, 1]


In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from warnings import filterwarnings
filterwarnings("ignore")


df=pd.DataFrame({"status": ["single", "married", "separated", "single","married"]})

In [4]:
df

,status
0,single
1,married
2,separated
3,single
4,married


In [5]:
encoder=OneHotEncoder()
encoder

OneHotEncoder()

In [6]:
encoded=encoder.fit_transform(df[["status"]]).toarray()
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [7]:
encoder.get_feature_names_out()
encoded_df=pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
encoded_df

,status_married,status_separated,status_single
0,0.0,0.0,1.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,0.0,0.0,1.0
4,1.0,0.0,0.0


In [8]:
encoder.transform([["single"]]).toarray()

array([[0., 0., 1.]])

In [9]:
pd.get_dummies(encoded_df, drop_first=True) 

,status_married,status_separated,status_single
0,0.0,0.0,1.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,0.0,0.0,1.0
4,1.0,0.0,0.0


In [10]:
final_df=pd.concat([df,encoded_df], axis=1)

In [11]:
import seaborn as sns

tips=sns.load_dataset("tips")


In [12]:
tips_df=encoder.fit_transform(tips[["sex","smoker","day","time"]]).toarray()
tips_df

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]], shape=(244, 10))

In [13]:
pd.DataFrame(tips_df, columns=encoder.get_feature_names_out())

,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
239,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
240,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
241,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
242,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0


In [14]:
#label encoding >> assign different labe to the categories

#using map and using libraries we can proceed


In [15]:
df

,status
0,single
1,married
2,separated
3,single
4,married


In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [17]:
encoded_df2=le.fit_transform(df['status'])
encoded_df2

array([2, 0, 1, 2, 0])

In [18]:
le.transform(["separated"])

array([1])

In [19]:
#ordinal encoding >> assign different labe to the categories based on the order
#example: low, medium, high
#High school=1
#graduation=2
#post graduation=3
#phd=4


In [20]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
df2=pd.DataFrame({"qualification": ["HS","GR","PG","PHD"]})
df2

,qualification
0,HS
1,GR
2,PG
3,PHD


In [22]:
oe=OrdinalEncoder(categories=[["HS","GR","PG","PHD"]])

In [23]:
oe.fit(df2[["qualification"]])

OrdinalEncoder(categories=[['HS', 'GR', 'PG', 'PHD']])

In [24]:
oe.fit_transform(df2[["qualification"]])

array([[0.],
       [1.],
       [2.],
       [3.]])

In [25]:
oe.transform([["GR"]])

array([[1.]])

In [26]:
#target guided ordinal encoding >> based on the target variable we can assign the order
#relationship with tgarget variable 
#A lot of categories
#replace the category with mean and median with respectative group


In [27]:
df3 = pd.DataFrame({
    'time': ["lunch", "breakfast", "dinner", "lunch", "breakfast", "dinner", "lunch", "breakfast", "dinner"],
    'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]
})
df3


,time,total_bill
0,lunch,120
1,breakfast,130
2,dinner,90
3,lunch,125
4,breakfast,150
5,dinner,190
6,lunch,160
7,breakfast,180
8,dinner,189


In [31]:
mean_price=df3.groupby("time")["total_bill"].mean().to_dict()


In [32]:
df3["time_encoded"]=df3['time'].map(mean_price)

In [ ]:
df3

,time,total_bill,time_encoded
0,lunch,120,135.000000
1,breakfast,130,153.333333
2,dinner,90,156.333333
3,lunch,125,135.000000
4,breakfast,150,153.333333
5,dinner,190,156.333333
6,lunch,160,135.000000
7,breakfast,180,153.333333
8,dinner,189,156.333333
