In [184]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [185]:
df = pd.read_csv("data/train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [186]:
# removing unneccessary columns
df.drop(columns=['Name','Ticket','Cabin','PassengerId'],inplace = True)

In [187]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,22.0,1,0,7.2500,S
1,1,1,female,38.0,1,0,71.2833,C
2,1,3,female,26.0,0,0,7.9250,S
3,1,1,female,35.0,1,0,53.1000,S
4,0,3,male,35.0,0,0,8.0500,S


In [188]:
# creating new column family adding two columns SibSp+Parch
df['family'] = df['SibSp']+df['Parch']

In [189]:
df.drop(columns=['SibSp','Parch'],inplace=True)
df.head()

,Survived,Pclass,Sex,Age,Fare,Embarked,family
0,0,3,male,22.0,7.2500,S,1
1,1,1,female,38.0,71.2833,C,1
2,1,3,female,26.0,7.9250,S,0
3,1,1,female,35.0,53.1000,S,1
4,0,3,male,35.0,8.0500,S,0


In [190]:
# checking null values
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
Fare          0
Embarked      2
family        0
dtype: int64

In [191]:
# we can fill this null values after train test split using SimpleImputer class by sklearn

In [192]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=42)

In [193]:
X_train.head()

,Pclass,Sex,Age,Fare,Embarked,family
331,1,male,45.5,28.5000,S,0
733,2,male,23.0,13.0000,S,0
382,3,male,32.0,7.9250,S,0
704,3,male,26.0,7.8542,S,1
813,3,female,6.0,31.2750,S,6


In [194]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [195]:
# hadling null values
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy = 'most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [196]:
# handling Categorical Column
ohe_sex = OneHotEncoder(sparse_output=False,handle_unknown = 'ignore')
ohe_embarked = OneHotEncoder(sparse_output=False,handle_unknown = 'ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.fit_transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.fit_transform(X_test_embarked)

In [197]:
# adding all things to train
X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

X_train_final = np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_final = np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

In [198]:
# making object of Decision Tree Classifier And fitting on data

clf = DecisionTreeClassifier()
clf.fit(X_train_final,y_train)

DecisionTreeClassifier()

In [199]:
#sklearn.ensemble.RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

clf_random = RandomForestClassifier()
clf_random.fit(X_train_final,y_train)

RandomForestClassifier()

In [200]:
y_predict_r = clf_random.predict(X_test_final)
y_predict_r

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1], dtype=int64)

In [201]:
y_predict = clf.predict(X_test_final)
y_predict

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1], dtype=int64)

In [202]:
acc = accuracy_score(y_test,y_predict)
print(f"Accuracy Score of Decsion Tree is {acc}")

Accuracy Score of Decsion Tree is 0.770949720670391


In [203]:
acc = accuracy_score(y_test,y_predict_r)
print(f"Accuracy Score of Random Forest is {acc}")

Accuracy Score of Random Forest is 0.8212290502793296


In [204]:
import pickle

pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf_random,open('models/clf.pkl','wb'))

# Predicating the values 

In [205]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [220]:
user_input = (np.array([2,10.2,0,22,'male','S'],dtype=object)).reshape(1,6)

In [221]:
ohe_sex_t = ohe_sex.transform(user_input[:,4].reshape(1,1))
ohe_sex_t

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [222]:
ohe_embarked_t = ohe_embarked.transform(user_input[:,5].reshape(1,1))

In [223]:
ohe_embarked_t

array([[0., 0., 1.]])

In [224]:
user_input_rem = user_input[:,:4]
user_input_rem

array([[2, 10.2, 0, 22]], dtype=object)

In [225]:
user_input_final = np.concatenate((user_input_rem,ohe_sex_t,ohe_embarked_t),axis=1)

In [226]:
clf.predict(user_input_final)

array([0], dtype=int64)