In [ ]:
# Summary :
# STEP 1 :
# STEP 2 :
# STEP 3 :
    # import libraries
    # meet dataa
    #Data Cleaning: 
        #Correcting --> We deal with outliers,aberrant values and making order.
        #Completing --> We have no null values so we will skip that part
        #Creating --> we do not need to creating new values so  we will skip that part
        #Converting --> We deal with labels
        
# STEP 4 : Perform Exploratory Analysis with Statistics
        #Corelation between discrete variables and  dependent variable.
        # Histogram
        # density graphs
        # evaluate dependent variables together with target variable
        # Corelation Matrix

# STEP 5 : Model Data
    # split test-train
    # Choose the best algorithm for that data (using pipline)
    # prediction with best algorithm
    # MODEL TUNİNG
    # Optimize the parameters for best algorithm
    # predict with tuned final model

## STEP 1 : Define The Problem
* We want to predict the diamond price.
* This is a regression problem.

## STEP 2 : Collect The Data,
* we take the date from Kaggle platform.

## STEP 3 : Preapare Data for Consumption
*

### 3.1 : Import Libraries

In [ ]:
#All the libralies 

import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn import svm, tree, linear_model, neighbors, ensemble
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from sklearn import metrics
from sklearn import model_selection
from sklearn.pipeline import Pipeline
from sklearn. linear_model import Lasso , Ridge ,ElasticNet
from lightgbm import LGBMRegressor
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


### >> 3.2 Meet  Data 

* The dataset contains the prices and other attributes of nearly 54,000 diamonds. There are 10 attributes
* Feature description:
* price : It ranges from $18,823 and $326.This is our outcome or dependent variable (target variable)--> y
* cut : It is related to physical attribute of diamonds and it is a categorical and ordinal variable.We can think that it is related to quality. -->Fair < Good < Very Good < Premium < Ideal
* color : J (worst) to D (best) - it is a categorical and ordinal variable
* carat : The carat is related to the diamond’s physical weight. It ranges from 0.2 and 5.01.
* clarity : I1 (worst), SI2, SI1, VS2, VS1, VVS2, VVS1, IF (best) --> it is a categorical and ordinal variable.
* Dimensions -> x,y,z
* x : length in mm (0--10.74)
* y : width in mm (0--58.9)
* z : depth in mm (0--31.8)
* depth : total depth percentage = z / mean(x, y) = 2 * z / (x + y) --> it ranges from (43--79)
* table : width of top of diamond relative to widest point (43--95) -> continious varible

In [ ]:
# import my data
diamond_data = pd.read_csv('/kaggle/input/diamonds/diamonds.csv')

#copy
data1 = diamond_data.copy()

In [ ]:
data1.head()

In [ ]:
# There are "unnamed" column but we actually know that it represent our index numbers.
#I mean it is supposed that the index numbers as variable
# We need to fix the problem.

In [ ]:
data1 = data1.iloc[:,1:len(data1)]
#  get the all observation --> :  
# then go to  1. from the length of dataframe. 1 : len(data1) 
# I use "iloc" because ı need to  arrange by indexes 
# alternative way to fix it --> data1 = data1.drop(["Unnamed: 0"], axis=1)

In [ ]:
data1.head()

In [ ]:
# I get some informations about my data
data1.info()

In [ ]:
data1.sample(10)

In [ ]:
data1.dtypes

In [ ]:
data1.shape
# 53940 observations and 10 variables

In [ ]:
# check variable names
data1.columns

In [ ]:
# check if my data has missing datas  or not
# train veri setimdeki eksik değerleri check ediyorum 
data1.isnull().sum()

 ### >>3.21 The 4 C's of Data Cleaning: Correcting, Completing, Creating, and Converting

In [ ]:
# In that part We also use data visualization techniques
# Correcting -> We deal with outliers,aberrant values and making order.
# Completing ->  we have no null values so we will skip that part
# Creating ->  we do not need to creating new values so  we will skip that part
# Conveting -> We deal with it (labels)

In [ ]:
data1.describe().T

In [ ]:
###Correcting 
# When we check it ,we can see that there are some aberrant values that means there are  dimensionless or 2-dimensional diamonds.
# We have to correct this

In [ ]:
# We should reach the index which x = 0 
data1 = data1.drop(data1[data1["x"]==0].index)

# We should reach the index which y = 0 
data1 = data1.drop(data1[data1["y"]==0].index)

# We should reach the index which z = 0 
data1 = data1.drop(data1[data1["z"]==0].index)

In [ ]:
# DO NOT  CONFUSED

In [ ]:
data1["x"][0]

In [ ]:
data1[data1["x"]==0].index

In [ ]:
data1.describe().T

In [ ]:
data1.shape
# we had 53940 observations before deleting x=0,y=0,z=0
# now we have  53920  observations
# We lost 20 observations.

In [ ]:
data1.head()

In [ ]:
# check outliars

In [ ]:
# ı want to see all corelation between all numeric variables.

In [ ]:
sns.pairplot(data1)
# you can also evalute by adding hue = "cut" or hue ="color" vs

In [ ]:
# when you look at the matrix you can decide from what number to delete this  but if you can hestite the decide the number you can use that way. !
# First take the values of the variables. --> data1["z"].values
# then count by usin numpy.sum function !

In [ ]:
data1["z"].values # values function returns us a numpy array
# you can check there --> type(data1["z"].values)

In [ ]:
z_nparray  = data1["z"].values
np.sum(z_nparray < 2.3) # I decided  2.3

In [ ]:
# same for "table " variables
table_nparray  = data1["table"].values
np.sum(table_nparray <51) # I decided  51

In [ ]:
# Summary: ı will drop according to these range 
# for y --> we can drop the variables y> 30
# for z --> we can drop the variables z> 30 and z <  2.3
# for depth --> we can drop the variables depth> 75 and depth <45
# for table --> we can drop the variables table> 90 and table <  51

data1 = data1[(data1["y"]<30)]
data1 = data1[(data1["z"]<30)&(data1["z"]>2.3)]
data1 = data1[(data1["depth"]<75)&(data1["depth"]>45)]
data1 = data1[(data1["table"]<80)&(data1["table"]>51)]

In [ ]:
data1.shape
# we had  53920 observations and 10 variables
# now we have 53882 observations and 10 variables
# we lost 38 observations

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data1.select_dtypes(include = ["object"]) # to see just categorical

In [ ]:
# we can see how many observations there are in each class

In [ ]:
data1["cut"].value_counts()

In [ ]:
data1["cut"].value_counts().plot.barh().set_title("Frequency of Cut Variable");
#w/pandas

In [ ]:
sns.barplot(x = "cut", y = data1.cut.index ,data = data1).set_title("Frequency of Cut Variable");
#w/seaborn

In [ ]:
data1["color"].value_counts()

In [ ]:
data1["color"].value_counts().plot.barh().set_title("Frequency of Color Variable");
#w/pandas

In [ ]:
sns.barplot(x = "color", y = data1.color.index ,data = data1).set_title("Frequency of Color Variable");
#w/seaborn

In [ ]:
data1["clarity"].value_counts()

In [ ]:
data1["clarity"].value_counts().plot.barh().set_title("Frequency of Clarity Variable");
#w/pandas

In [ ]:
sns.barplot(x = "clarity", y = data1.clarity.index ,data = data1).set_title("Frequency of Clarity Variable");
#w/seaborn

In [ ]:
 #Completing ->  we have no null values so we will skip that part

In [ ]:
# Creating -> We do not create new variable

In [ ]:
# Converting
# label endocoding for categorical varibales

In [ ]:
# Firstly get the categorical data in the dataset and make a list.

In [ ]:
# get the objects in dataset
my_object = data1.dtypes == object

# get the indexes of object
my_object2 = my_object[my_object].index

# to the list
list_objects = list(my_object2)
list_objects

In [ ]:
#my_object[my_object].index

In [ ]:
#list(my_object2)

In [ ]:
 data_label = data1.copy()

In [ ]:
data1

In [ ]:
label = LabelEncoder() #

for i in list_objects: 
    data_label[i] = label.fit_transform(data_label[i])
    
# dataset['cut'] = label.fit_transform(dataset['cut'])..

In [ ]:
data_label.head()

In [ ]:
data2 = data_label.copy()

In [ ]:
data2.head()

In [ ]:
data2.describe()

## Step 4: Perform Exploratory Analysis with Statistics

In [ ]:
print("carat:",data1["carat"].dtype)
print("cut:",data1["cut"].dtype)
print("color:",data1["color"].dtype)
print("clarity:",data1["clarity"].dtype)
print("depth:",data1["depth"].dtype)
print("table:",data1["table"].dtype)
print("price:",data1["price"].dtype)
print("x:",data1["x"].dtype)
print("y:",data1["y"].dtype)
print("z:",data1["z"].dtype)

In [ ]:
Target_variable  = ["price"] # get my target/dependent variable

In [ ]:
data2_x = ['carat','cut','color','clarity','depth','table','x','y','z']

In [ ]:
data2[["cut", Target_variable[0]]]

In [ ]:
data2[["cut", Target_variable[0]]].groupby("cut", as_index=False).mean()

In [ ]:
#Corelation between discrete variables and  dependent variable.
# Group by kullnarak discrete değişkenlerin ; bağımlı y değişkeni "price" ile olan ilişkileri ;
# For döngüsü ile bağımısz değişkenimi içeren değişken içinde geziniorum

for x in data2_x: # bütün bağımsız değişkenler burada -> data2_x 
    if data1[x].dtype != 'float64' : 
        print('Survival Correlation by:', x)
        print(data1[[x, Target_variable[0]]].groupby(x, as_index=False).mean())
        print('-'*10, '\n')
        
# If we use "data1" , we can see the categorical name as "fair","good" etc.
# If we use "data2" , we can see the numerical  as 1,2 etc. becase we applied to label encoding to data2. !

In [ ]:
data1[data2_x]

In [ ]:
data2[data2_x]

In [ ]:
#Corelation between categorical variables and  each other

In [ ]:
pd.crosstab(data2['cut'],data2['color'])

In [ ]:
# Data Visualization

In [ ]:
#graph distribution of quantitative data
# Sayısal verilerin grafikleri;

plt.figure(figsize=[16,12]) #aşağıdaki tabloların büyüklüğü ile ilgili ayarlama


# subplot(x,y,z) : Grafiklerin düzlemini ve kaçıncı grafik olduğunu belirtir. 
#İlk sayı satırı, ikinci sayı sütunu, üçüncü sayı ise kaçıncı grafik olduğunu ifade eder
# buradaki subplot aşağıdaki çıktının nasıl görüneceğine karar verir 
        # (231) --> 2 satır olsun 3 sütün olsun ve bu tablo 1. sırada olsun gibi
        # (322) --> 3 satır olsun 2 sütün olsun ve bu tablo 2. sırada olsun gibi


# x ekseninze veri setimizin içinden istediğim bağımsız değişkeni seçiyorum
plt.subplot(231) 
plt.boxplot(x=data2['carat'], showmeans = True, meanline = True)                       
plt.title('carat Boxplot') 
plt.legend();

#depth
plt.subplot(232) #  plt.subplot(2,3,1) ile aynı sonucu verir.
plt.boxplot(x=data2['depth'], showmeans = True, meanline = True)                      
plt.title('depth Boxplot') 


#table
plt.subplot(233) 
plt.boxplot(x=data2['table'], showmeans = True, meanline = True)                       
plt.title('table Boxplot') 
plt.legend();


In [ ]:
# evalute the categorical variable with dependent variable

In [ ]:
#catplots

In [ ]:
sns.catplot(x = "cut",y = "price",data = data1);

In [ ]:
sns.catplot(x = "color",y = "price",data = data1);

In [ ]:
sns.catplot(x = "clarity",y = "price",data = data1);

In [ ]:
# violin

In [ ]:
sns.catplot(y = "price", kind ="violin",data = data1);

In [ ]:
sns.catplot(y = "depth", kind ="violin",data = data1);

In [ ]:
sns.catplot(y = "table", kind ="violin",data = data1);

In [ ]:
# evaluate dependent variables together with target variable
fig, saxis = plt.subplots(2, 3,figsize=(16,12))

# x ekseninde bağımsız değişkenler
# y ekseninde bağımlı değişkenler
# "data" argümanına barplot çizeceğim verimi koyuyorum
# "ax" argümanına yukarıda tanımladıgım "saxis" değişkenini koydum ve o grafiğin konumunu belirledim
# ax = saxis[0,0] --> x için 0. idex ; y için 0. index


sns.barplot(x = "cut", y ="price", hue = "color",data=data1, ax = saxis[0,0])
sns.barplot(x = "color", y ="price", hue = "cut",data=data1, ax = saxis[0,1])
sns.barplot(x = "cut", y ="price", hue = "clarity",data=data1, ax = saxis[0,2]);

# pointplot çiziyorum

sns.pointplot(x = 'cut', y = 'price',hue = "color",  data=data1, ax = saxis[1,0])
sns.pointplot(x = 'color', y = 'price',hue = "cut"  ,data=data1, ax = saxis[1,1])
sns.pointplot(x = 'cut', y = 'price',hue = "clarity", data=data1, ax = saxis[1,2]);


In [ ]:
# density graphs

In [ ]:
fig, saxis = plt.subplots(2, 3,figsize=(16,12))

sns.distplot(data1.price, ax = saxis[0,0]);
sns.distplot(data1.x, ax = saxis[0,1]);
sns.distplot(data1.y,kde=False , ax = saxis[0,2]);
sns.distplot(data1.z , ax = saxis[1,0]);
sns.distplot(data1.depth ,  ax = saxis[1,1]);
sns.distplot(data1.table ,  ax = saxis[1,2]);

In [ ]:
# Histogram

In [ ]:
fig, saxis = plt.subplots(2, 3,figsize=(16,12))

sns.histplot(data1.price, ax = saxis[0,0]);
sns.histplot(data1.x, ax = saxis[0,1]);
sns.histplot(data1.y,kde=False , ax = saxis[0,2]);
sns.histplot(data1.z , ax = saxis[1,0]);
sns.histplot(data1.depth ,  ax = saxis[1,1]);
sns.histplot(data1.table ,  ax = saxis[1,2]);

In [ ]:
# evaluate dependent variables together with target variable

In [ ]:
# Bağımlı y "price" değişkenin cut göre dağılımı
# yani hayatta kalan veya hayatta kalmayan yolcuların yaş dağılımlarını
a = sns.FacetGrid( data1, hue = 'cut', aspect=4 )
    # ilk argüman olarak veri setimizi ; bağımlı değişkeni koyarız
    # aspect argümanı grafiğin x ekseninde ne kadar yayılacağını belirliyor..
        #...aralıklar aynı amaa görüntü olarak değiştiriyor
    # Olusturdugumuz grafiğin x ve y eksenini ayarlayabiliriz    

#map fonksiyonu ile ilk olarak fonksiyon koyarsın ve ardından elimizdeki bir datanın elemanlarını koyarız..
#..ve bize bir obje döndürür
#Burada biz seaborn un kdeplot fonksiyonu kullanarak price e göre kdeplot grafiği oluşturucaz            

#...ve ile "map" ile eşleyecez

a.map(sns.kdeplot, 'price', shade= True )
        # shade=True diyerek de her bir grafiğin altındaki alanı boyuyacak
a.add_legend()

In [ ]:
a = sns.FacetGrid( data2, hue = 'color', aspect=4 )
a.map(sns.kdeplot, 'price', shade= True )
a.add_legend()

In [ ]:
a = sns.FacetGrid( data2, hue = 'clarity', aspect=4 )
a.map(sns.kdeplot, 'price', shade= True )
a.add_legend()

In [ ]:
def correlation_heatmap(df):
    _ , ax = plt.subplots(figsize =(14, 12))
    colormap = sns.diverging_palette(220, 10, as_cmap = True)
    
    _ = sns.heatmap(
        df.corr(), 
        cmap = colormap,
        square=True, 
        cbar_kws={'shrink':.9 }, #sağ kısımdaki renk scalası
        ax=ax,
        annot=True, #ısı hartiasının her hücresini sayılar ile doldurabilir
        linewidths=0.1,vmax=1.0, linecolor='white', # kutular arasında çizgi çeker
        annot_kws={'fontsize':12 }
    )
    
    plt.title('Pearson Correlation of Features', y=1.05, size=15)

correlation_heatmap(data1)

# more simple alternative
#correlation matrix
#cmap = sns.diverging_palette(70,20,s=50, l=40, n=6,as_cmap=True)
#corrmat= label_data.corr()
#f, ax = plt.subplots(figsize=(12,12))
#sns.heatmap(corrmat,cmap=cmap,annot=True, )

## STEP 5 : Model Data

In [ ]:
data2.head()

In [ ]:
# Assigning the featurs as X and trarget as y
X= data2.drop(["price"],axis =1)
y= data2["price"]
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20, random_state=0)
Target = ["price"]

In [ ]:
# Building pipelins of standard scaler and model for varios regressors.

pipeline_lr=Pipeline([("scalar1",StandardScaler()),
                     ("lr",LinearRegression())])

pipeline_lasso=Pipeline([("scalar2", StandardScaler()),
                      ("lasso",Lasso())])

pipeline_Ridge=Pipeline([("scalar3", StandardScaler()),
                      ("Ridge",Ridge())])

pipeline_Elastic=Pipeline([("scalar4", StandardScaler()),
                      ("ElasticNet",ElasticNet())])

pipeline_PCA=Pipeline([("scalar5", StandardScaler()),
                      ("PCA",PCA())])

pipeline_dt=Pipeline([("scalar6",StandardScaler()),
                     ("dt",DecisionTreeRegressor())])

pipeline_rf=Pipeline([("scalar7",StandardScaler()),
                     ("rf",RandomForestRegressor())])


pipeline_kn=Pipeline([("scalar8",StandardScaler()),
                     ("kn",KNeighborsRegressor())])


pipeline_xgb=Pipeline([("scalar9",StandardScaler()),
                     ("xgb",XGBRegressor())])

pipeline_Lightgbm =Pipeline([("scalar6",StandardScaler()),
                     ("Lightgbm",LGBMRegressor())])


# List of all the pipelines
pipelines = [pipeline_lr, pipeline_lasso ,pipeline_Ridge ,pipeline_Elastic ,pipeline_PCA , pipeline_dt, pipeline_rf, pipeline_kn, pipeline_xgb,pipeline_Lightgbm]

# Dictionary of pipelines and model types for ease of reference
pipe_dict = {0: "LinearRegression", 1: "Lasso", 2: "Ridge",3: "ElasticNet", 4: "PCA",5: "DecisionTree",6: "RandomForest",7: "KNeighbors",8: "XGBoost", 9 :"Lightgbm"}

# Fit the pipelines
for pipe in pipelines:
    pipe.fit(X_train, y_train)

In [ ]:
#pipe_dict[1]
# output : 'Lasso'

In [ ]:
#cv_score
# output :  array([-529.43455215, -559.84023247, -532.97260133, -538.15760957,
#       -541.44238589, -566.00715293, -539.84836841, -570.07039353,
#       -556.95823504, -497.88947571])

In [ ]:
#cv_results_rms
# output : [array([-1298.7483982 , -1372.54690623, -1378.01074736, -1317.97109566,
#        -1364.59329838, -1338.74316099, -1319.39806228, -1351.7467537 ,
#        -1353.28136622, -1374.27707865]),
# array([-1293.25444289, -1378.06918668, -1380.63990024, -1322.28581959,
#        -1362.34955928, -1341.9472592 , -1320.23910978, -1352.13765997,
#        -1355.112188  , -1376.99909873]),
# array([-1297.89317926, -1372.84562301, -1378.08899769, -1318.22381492,
#       -1364.2873263 , -1338.91503362, -1319.2711774 , -1351.47960295,
#        -1353.33965343, -1374.38415   ]),
# array([-1640.96112263, -1719.03692007, -1717.87382301, -1614.15693317,
#        -1673.52530911, -1688.02217792, -1668.8519602 , -1635.68128477,
#        -1669.97658452, -1678.14948559]),
# array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]),
# array([-715.15601211, -753.6575892 , -774.97595428, -755.96211754,
#-733.81419448, -762.93421428, -721.85702825, -770.77466463,
#        -756.06991376, -769.07825374]),
# array([-547.13429738, -561.45261488, -553.05633934, -542.40518805,
#        -544.82003959, -573.51606368, -529.73653323, -565.77677425,
#        -583.86560214, -526.94873295]),
# array([-784.49980591, -923.80197514, -826.50592365, -795.79665318,
#        -870.82428913, -842.26627556, -859.41598283, -817.63907412,
#        -848.84263715, -788.60926571]),
# array([-532.88501622, -562.00070108, -549.17278827, -547.09178207,
#        -543.02853017, -578.53850858, -528.67649939, -561.1215002 ,
#        -576.61208715, -520.95148598]),
# array([-529.43455215, -559.84023247, -532.97260133, -538.15760957,
#        -541.44238589, -566.00715293, -539.84836841, -570.07039353,
#        -556.95823504, -497.88947571])]

In [ ]:
#list(enumerate(pipelines))
# output :
# [(0,
#  Pipeline(steps=[('scalar1', StandardScaler()), ('lr', LinearRegression())])),
# (1, Pipeline(steps=[('scalar2', StandardScaler()), ('lasso', Lasso())])),
# (2, Pipeline(steps=[('scalar3', StandardScaler()), ('Ridge', Ridge())])),
# (3,
#  Pipeline(steps=[('scalar4', StandardScaler()), ('ElasticNet', ElasticNet())])),
# (4, Pipeline(steps=[('scalar5', StandardScaler()), ('PCA', PCA())])),
# (5,
#  Pipeline(steps=[('scalar6', StandardScaler()), ('dt', DecisionTreeRegressor())])),
# (6,
#  Pipeline(steps=[('scalar7', StandardScaler()), ('rf', RandomForestRegressor())])),
# (7,
#  Pipeline(steps=[('scalar8', StandardScaler()), ('kn', KNeighborsRegressor())])),
# (8,
#  Pipeline(steps=[('scalar9', StandardScaler()),
#                  ('xgb',
#                  XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
#                                colsample_bylevel=1, colsample_bynode=1,
#                                colsample_bytree=1, early_stopping_rounds=None,
#                                enable_categorical=False, eval_metric=None,
#                                gamma=0, gpu_id=-1, grow_policy='depthwise',
#                                importance_type=None, interaction_constraints='',
#                                learning_rate=0.300000012, max_bin=256,
#                                max_cat_to_onehot=4, max_delta_step=0,
#                                max_depth=6, max_leaves=0, min_child_weight=1,
#                                missing=nan, monotone_constraints='()',
#                                n_estimators=100, n_jobs=0, num_parallel_tree=1,
#                                predictor='auto', random_state=0, reg_alpha=0,
#                                reg_lambda=1, ...))])),
# (9,
#  Pipeline(steps=[('scalar6', StandardScaler()), ('Lightgbm', LGBMRegressor())]))]

In [ ]:
#model.__class__.__name__
#output: 'Pipeline'

In [ ]:
# pipe
#output: Pipeline(steps=[('scalar7', StandardScaler()), ('rf', RandomForestRegressor())])

In [ ]:
MLA_columns = ['MLA Name','neg_root_mean_squared_error']

MLA_compare = pd.DataFrame(columns = MLA_columns)

cv_results_rms = []
for i, model in enumerate(pipelines):
        # enumarate -->  (0,Pipeline(steps=[('scalar1', StandardScaler()),('lr', LinearRegression())]))
    cv_score = -cross_val_score(model, X_train,y_train,scoring="neg_root_mean_squared_error", cv=10)
    cv_results_rms.append(cv_score)
    MLA_compare.loc[i, 'MLA Name'] = pipe_dict[i]
    MLA_compare.loc[i, 'neg_root_mean_squared_error'] = cv_score.mean()
   
    
MLA_compare    

In [ ]:
MLA_compare.sort_values(by = ['neg_root_mean_squared_error'], inplace = True)
MLA_compare

In [ ]:
# 'Machine Learning Algorithm on table
sns.barplot(x='neg_root_mean_squared_error', y = 'MLA Name', data = MLA_compare, color = 'b')
plt.title('Machine Learning Algorithm neg_root_mean_squared_error \n')
plt.xlabel('neg_root_mean_squared_error')
plt.ylabel('Algorithm')

In [ ]:
# Model prediction on test data
# Testing the Model with the best score on the test set
y_pred = pipeline_Lightgbm.predict(X_test,num_iteration = pipeline_Lightgbm[1].best_iteration_)

In [ ]:
pipeline_Lightgbm

In [ ]:
print("R^2:",metrics.r2_score(y_test, y_pred))
print("Adjusted R^2:",1 - (1-metrics.r2_score(y_test, y_pred))*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1))
print("MAE:",metrics.mean_absolute_error(y_test, y_pred))
print("MSE:",metrics.mean_squared_error(y_test, y_pred))
print("RMSE:",np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

In [ ]:
# LightGBM - Model Tuning

In [ ]:
pipeline_Lightgbm.get_params()

In [ ]:
# Optimize the parameters

In [ ]:
lgbm_grid = {
'Lightgbm__colsample_bytree': [0.4, 0.5,0.6,0.9,1],
'Lightgbm__learning_rate': [0.01, 0.1, 0.5,1],
'Lightgbm__n_estimators': [20, 40, 100, 200, 500,1000],
'Lightgbm__max_depth': [-1,1,2,3,4,5,6,7,8] }

In [ ]:
lgbm_cv_model = GridSearchCV(pipeline_Lightgbm, lgbm_grid, cv=10, n_jobs = -1, verbose = 2)

In [ ]:
lgbm_cv_model.fit(X_train, y_train)

In [ ]:
# check the optimum parameter values
lgbm_cv_model.best_params_

In [ ]:
# set the final model by using optimal parameter values.
lgbm_tuned = LGBMRegressor(Lightgbm__learning_rate = 0.5,
Lightgbm__n_estimators = 8,
Lightgbm__colsample_bytree = 0.9)

In [ ]:
# fit the final tuned model
lgbm_tuned = lgbm_tuned.fit(X_train,y_train) # final modelini fit ettim

In [ ]:
#final modelim ile tahmin
y_pred = lgbm_tuned.predict(X_test)

In [ ]:
#neg_root_mean_squared_error
np.sqrt(mean_squared_error(y_test, y_pred))

In [ ]:
print("R^2:",metrics.r2_score(y_test, y_pred))
print("Adjusted R^2:",1 - (1-metrics.r2_score(y_test, y_pred))*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1))
print("MAE:",metrics.mean_absolute_error(y_test, y_pred))
print("MSE:",metrics.mean_squared_error(y_test, y_pred))
print("RMSE:",np.sqrt(metrics.mean_squared_error(y_test, y_pred)))