# My Solutions for Numpy Fun Problems - Expert

Welcome to my in-depth exploration of the "Expert" level Numpy practice problems. This set is designed for those who seek to push the boundaries of their Numpy proficiency to the highest level. Engage with these expert challenges by visiting:

- [Practice Problems Source](https://www.practiceprobs.com/problemsets/python-numpy/expert/)

Tackling these expert problems signifies your commitment to mastering Numpy. If you are progressing from the "Advanced" level and wish to continue honing your skills, this set will provide you with the rigorous challenges you need. If you need to reference or revisit the "Advanced" level for additional practice or clarification, you can find those solutions here:

- [Previous Notebook: Numpy Fun Problems - Advanced](https://www.kaggle.com/code/matinmahmoodi/numpy-fun-problems-advanced)

I highly value your contributions and perspectives. Sharing your solutions, insights, or any feedback in the comments enriches our collective learning experience. Let's collaborate to conquer these expert challenges!

### **If this notebook serves as a valuable resource in your learning journey, please acknowledge it with an upvote!**


# Q1 - One-Hot-Encoding Problem

https://www.practiceprobs.com/problemsets/python-numpy/expert/one-hot-encoding/

Given a 1d array of integers, one-hot-encode it into a 2d array. In other words, convert this 1-d array called yoyoyo,


In [ ]:
import numpy as np
yoyoyo = np.array([3, 1, 0, 1])


into a 2-d array like this.



In [ ]:
# [[0. 0. 0. 1.]
#  [0. 1. 0. 0.]
#  [1. 0. 0. 0.]
#  [0. 1. 0. 0.]]

## Solution

In [ ]:
np.eye(np.max(yoyoyo) + 1)[yoyoyo]

## Q2 - Cumulative Rainfall Problem

https://www.practiceprobs.com/problemsets/python-numpy/expert/cumulative-rainfall/

Your job is to monitor the rainfall 🌧 in a region that you’ve broken into a 3x4 grid. Every time a storm comes, if a cell in the grid gets rain, you record it. At the end of a month you have the following two arrays of data.

In [ ]:
import numpy as np

rain_locations = np.array([
    [2,3],
    [0,1],
    [2,2],
    [2,3],
    [1,1],
    [2,3],
    [1,1]
])

rain_amounts = np.array([0.5,1.1,0.2,0.9,1.3,0.4,2.0])

Build a 3x4 array representing the total accumulated rainfall in each cell of the grid.

## Solution 1

In [ ]:
accumulated_rainfall = np.zeros((3, 4))

for i in range(len(rain_locations)):
    row = rain_locations[i][0]
    col = rain_locations[i][1]
    accumulated_rainfall[row][col] += rain_amounts[i]

accumulated_rainfall

## Solution 2 - more professional

In [ ]:
rainfall = np.zeros((3,4))
np.add.at(rainfall, (rain_locations[:, 0], rain_locations[:, 1]), rain_amounts)

rainfall

# Q3 - Table Tennis Problem

https://www.practiceprobs.com/problemsets/python-numpy/expert/table-tennis/

You manage a recreational table tennis league . There are 10 participants, and in an effort to make the first round of matchups as exciting as possible, you develop a model that predicts the score difference for every possible pair of players. That is, you produce a 10x10 matrix where (i,j) represents your prediction for player i’s score minus player j’s score if they were to compete.



In [ ]:
import numpy as np

generator = np.random.default_rng(0)
score_diffs = np.round(generator.uniform(low=-15, high=15, size=(10,10)), 2)
np.fill_diagonal(score_diffs, np.nan)
score_diffs[np.triu_indices(10, k=1)[::-1]] = -score_diffs[np.triu_indices(10, k=1)]

print(score_diffs)

Given this matrix, determine the “best” schedule for round one - the schedule whose matchups minimize the sum of squared point differentials.

## Solution

In [ ]:
from itertools import permutations

perms = np.array(list(permutations([0,1,2,3,4,5,6,7,8,9])))
mask = np.all(perms[:, ::2] < perms[:, 1::2], axis=1)
distincts = perms[mask]
point_diffs = score_diffs[distincts[:, ::2], distincts[:, 1::2]]
schedule_scores = np.sum(point_diffs**2, axis=1)
best_idx = np.argmin(schedule_scores)
best_schedule = distincts[best_idx]
best_matchups = np.stack((best_schedule[::2], best_schedule[1::2]), axis=1)

print(best_matchups)

# Q4 - Where's Waldo Problem


Given a 1-million element array where each element is a random character in a-z, identify the starting index of every sequence of characters that spells ‘waldo’. Include sequences where at least 4 of the 5 characters match (e.g. ‘waldo’, 'wafdo', and ‘xaldo’ but not ‘wadlo’).

https://www.practiceprobs.com/problemsets/python-numpy/expert/wheres-waldo/

In [ ]:
import numpy as np
import string

generator = np.random.default_rng(123)
chars = generator.choice(list(string.ascii_lowercase), size=10**6, replace=True)

print(chars[:10])


## Solution 

In [ ]:
windows = np.lib.stride_tricks.as_strided(
    x = chars,
    shape = (len(chars) - (5-1), 5),
    strides = (chars.strides[0], chars.strides[0])
)
waldo = np.array(['w','a','l','d','o'], dtype='<U1')
start_idxs = np.where((windows == waldo).sum(axis=1) >= 4)[0]

print(start_idxs)


# Q5 - Outer Product Problem

https://www.practiceprobs.com/problemsets/python-numpy/expert/outer-product/

Calculate the element-wise outer product of two matrices, A & B.

In [ ]:
import numpy as np

A = np.arange(10*3).reshape((10,3))
B = np.arange(10*5).reshape((10,5))

print(A)
print(B)


## Solution

In [ ]:
a = A.shape[-1]
b = B.shape[-1]
d = A.strides[-1]
new_shape = A.shape + (b,)
As = np.lib.stride_tricks.as_strided(A, shape=new_shape, strides=(a*d, d, 0))
Bs = np.lib.stride_tricks.as_strided(B, shape=new_shape, strides=(b*d, 0, d))
result = As * Bs
result

# Q6 - Neural Network Convolution Problem

https://www.practiceprobs.com/problemsets/python-numpy/expert/neural-network-convolution/

Suppose you have a 2-D array, arr

In [ ]:
import numpy as np

arr = np.array([
    [0.15, 0.71, 0.26, -0.11, -2.03],
    [0.13, 0.44, -0.11, -0.23, 0.19],
    [-1.44, 0.51, 0.42, 2.58, -0.88],
    [-1.18, 2.73, 2.35, 0.21, -0.29],
    [-1.64, -0.37, 0.27, 0.57, 1.82]
])


and another, smaller 2-D array, filter

In [ ]:
filter = np.array([
    [0.08, 0.27, -0.24],
    [-0.25, -0.11, -0.18],
    [0.44, 1.87, 1.18]
])

In the context of neural networks, a convolution works by "sliding" filter over arr in row major order (left to right, top to bottom), taking the dot product between filter and the portion of arr it covers at each step.



![](https://www.practiceprobs.com/problemsets/python-numpy/images/convolution.gif)

The result of all these dot products is the following 3x3 array.

Now suppose arr is the following 33x33x3 array

In [ ]:
import numpy as np

rng = np.random.default_rng(123)
arr = rng.normal(size=(33,33,3)).round(2)

print(arr)

And let filter be the following 5x5x3 array.



In [ ]:
filter = rng.normal(size=(5,5,3)).round(2)

print(filter)


Using strides of length two , calculate the convolution between these arrays. (The result should have shape 15x15.)

## Solution

In [ ]:
result = np.empty((15,15))
for i in range(0, 33 - 4, 2):
    for j in range(0, 33 - 4, 2):
        idxs = np.ix_(np.arange(i, i + 5), np.arange(j, j + 5))
        temp = arr[idxs]
        result_i, result_j = i//2, j//2
        result[result_i, result_j] = np.sum(temp * filter)

print(result)

Wait for more...